"""Gelişim yorum havuzu içeriği (F3) — 31 değişken × 5 aralık = 155 satır

Revision ID: 0004_gelisim_yorum_havuzu
Revises: 0003_31_degisken_icerik
Create Date: 2026-08-13

NOT — P4 (Nevrotiklik) icin acik soru: bu degiskende yuksek ogrenci puaninin
"ustun" sayilmasi diger 30 degiskenle ayni yonde yorumlanamaz (bkz. icerik
kaynak dosyasindaki not, icerik/gelisim_yorum_havuzu.py). Bu satirlar
simdilik standart yonle yazildi, aksiyon_onerisi alanlari bilincli olarak
NULL birakildi (aksiyon onerecek kadar yonu netlesmemis) - ekip onayi gerekiyor.
"""
from alembic import op

revision = "0004_gelisim_yorum_havuzu"
down_revision = "0003_31_degisken_icerik"
branch_labels = None
depends_on = None


def upgrade():
    _satirlar = [
        ("D1", "belirgin_ustun"),
        ("D1", "ustun"),
        ("D1", "beklenti"),
        ("D1", "altinda"),
        ("D1", "belirgin_altinda"),
        ("D2", "belirgin_ustun"),
        ("D2", "ustun"),
        ("D2", "beklenti"),
        ("D2", "altinda"),
        ("D2", "belirgin_altinda"),
        ("D3", "belirgin_ustun"),
        ("D3", "ustun"),
        ("D3", "beklenti"),
        ("D3", "altinda"),
        ("D3", "belirgin_altinda"),
        ("D4", "belirgin_ustun"),
        ("D4", "ustun"),
        ("D4", "beklenti"),
        ("D4", "altinda"),
        ("D4", "belirgin_altinda"),
        ("D5", "belirgin_ustun"),
        ("D5", "ustun"),
        ("D5", "beklenti"),
        ("D5", "altinda"),
        ("D5", "belirgin_altinda"),
        ("D6", "belirgin_ustun"),
        ("D6", "ustun"),
        ("D6", "beklenti"),
        ("D6", "altinda"),
        ("D6", "belirgin_altinda"),
        ("D7", "belirgin_ustun"),
        ("D7", "ustun"),
        ("D7", "beklenti"),
        ("D7", "altinda"),
        ("D7", "belirgin_altinda"),
        ("P1", "belirgin_ustun"),
        ("P1", "ustun"),
        ("P1", "beklenti"),
        ("P1", "altinda"),
        ("P1", "belirgin_altinda"),
        ("P2", "belirgin_ustun"),
        ("P2", "ustun"),
        ("P2", "beklenti"),
        ("P2", "altinda"),
        ("P2", "belirgin_altinda"),
        ("P3", "belirgin_ustun"),
        ("P3", "ustun"),
        ("P3", "beklenti"),
        ("P3", "altinda"),
        ("P3", "belirgin_altinda"),
        ("P4", "belirgin_ustun"),
        ("P4", "ustun"),
        ("P4", "beklenti"),
        ("P4", "altinda"),
        ("P4", "belirgin_altinda"),
        ("P5", "belirgin_ustun"),
        ("P5", "ustun"),
        ("P5", "beklenti"),
        ("P5", "altinda"),
        ("P5", "belirgin_altinda"),
        ("P6", "belirgin_ustun"),
        ("P6", "ustun"),
        ("P6", "beklenti"),
        ("P6", "altinda"),
        ("P6", "belirgin_altinda"),
        ("P7", "belirgin_ustun"),
        ("P7", "ustun"),
        ("P7", "beklenti"),
        ("P7", "altinda"),
        ("P7", "belirgin_altinda"),
        ("P8", "belirgin_ustun"),
        ("P8", "ustun"),
        ("P8", "beklenti"),
        ("P8", "altinda"),
        ("P8", "belirgin_altinda"),
        ("I1", "belirgin_ustun"),
        ("I1", "ustun"),
        ("I1", "beklenti"),
        ("I1", "altinda"),
        ("I1", "belirgin_altinda"),
        ("I2", "belirgin_ustun"),
        ("I2", "ustun"),
        ("I2", "beklenti"),
        ("I2", "altinda"),
        ("I2", "belirgin_altinda"),
        ("I3", "belirgin_ustun"),
        ("I3", "ustun"),
        ("I3", "beklenti"),
        ("I3", "altinda"),
        ("I3", "belirgin_altinda"),
        ("I4", "belirgin_ustun"),
        ("I4", "ustun"),
        ("I4", "beklenti"),
        ("I4", "altinda"),
        ("I4", "belirgin_altinda"),
        ("I5", "belirgin_ustun"),
        ("I5", "ustun"),
        ("I5", "beklenti"),
        ("I5", "altinda"),
        ("I5", "belirgin_altinda"),
        ("I6", "belirgin_ustun"),
        ("I6", "ustun"),
        ("I6", "beklenti"),
        ("I6", "altinda"),
        ("I6", "belirgin_altinda"),
        ("I7", "belirgin_ustun"),
        ("I7", "ustun"),
        ("I7", "beklenti"),
        ("I7", "altinda"),
        ("I7", "belirgin_altinda"),
        ("A1", "belirgin_ustun"),
        ("A1", "ustun"),
        ("A1", "beklenti"),
        ("A1", "altinda"),
        ("A1", "belirgin_altinda"),
        ("A2", "belirgin_ustun"),
        ("A2", "ustun"),
        ("A2", "beklenti"),
        ("A2", "altinda"),
        ("A2", "belirgin_altinda"),
        ("A3", "belirgin_ustun"),
        ("A3", "ustun"),
        ("A3", "beklenti"),
        ("A3", "altinda"),
        ("A3", "belirgin_altinda"),
        ("A4", "belirgin_ustun"),
        ("A4", "ustun"),
        ("A4", "beklenti"),
        ("A4", "altinda"),
        ("A4", "belirgin_altinda"),
        ("A5", "belirgin_ustun"),
        ("A5", "ustun"),
        ("A5", "beklenti"),
        ("A5", "altinda"),
        ("A5", "belirgin_altinda"),
        ("A6", "belirgin_ustun"),
        ("A6", "ustun"),
        ("A6", "beklenti"),
        ("A6", "altinda"),
        ("A6", "belirgin_altinda"),
        ("A7", "belirgin_ustun"),
        ("A7", "ustun"),
        ("A7", "beklenti"),
        ("A7", "altinda"),
        ("A7", "belirgin_altinda"),
        ("A8", "belirgin_ustun"),
        ("A8", "ustun"),
        ("A8", "beklenti"),
        ("A8", "altinda"),
        ("A8", "belirgin_altinda"),
        ("A9", "belirgin_ustun"),
        ("A9", "ustun"),
        ("A9", "beklenti"),
        ("A9", "altinda"),
        ("A9", "belirgin_altinda"),
    ]
    _sql = [
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Güvenceyi çok önemsiyorsun — düzenli, öngörülebilir bir kariyer arayışın net.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D1'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'İş güvencesine önem veriyorsun, kararlarında bu belirgin bir yer tutuyor.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D1'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Güvence ihtiyacın orta düzeyde — ne tamamen risk almaktan kaçınıyor ne de umursamıyorsun.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D1'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Güvence senin için önceliklerin arasında değil, bu bazı bölümlerde beklenmedik bir uyumsuzluğa yol açabilir.', 'Hedeflediğin bölümün gerçek iş piyasası koşullarını (istihdam oranı, sektör istikrarı) araştırmak, bu farkın seni nasıl etkileyeceğini görmene yardımcı olur.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'D1'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Güvence kaygısı senin motivasyon haritanda neredeyse hiç yer tutmuyor — bu bazı meslek gruplarında (kamu, güvence ağırlıklı sektörler) ciddi bir uyum farkı yaratabilir.', 'Hedef bölümün mezunlarının kariyer güzergahlarını (girişimcilik mi, kurumsal mı) incelemek gerçekçi bir beklenti oluşturur.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'D1'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Yüksek gelir senin için güçlü bir motivasyon kaynağı — kariyer kararlarında belirleyici bir ağırlığı var.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D2'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Ekonomik getiriye önem veriyorsun, tercihlerinde bu göz önünde bulunduruluyor.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D2'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Gelir düzeyi senin için orta derecede önemli — tek başına belirleyici değil.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D2'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Yüksek gelir motivasyonun düşük, bu bazı yüksek kazançlı ama yoğun tempolu alanlarda beklenti uyumsuzluğuna yol açabilir.', 'Hedef bölümün gerçek maaş aralıklarını araştırmak, kariyer kararını netleştirir.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'D2'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Ekonomik kazanç senin için neredeyse hiç önemli değil — yüksek gelirli ama anlam bakımından zayıf bulabileceğin alanlarda dikkatli olmalısın.', 'Kendine ''bu meslekte parasal olmayan hangi kazanımlar beni tatmin eder'' sorusunu sormak faydalı olabilir.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'D2'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Statü ve toplumsal tanınırlık senin için çok belirleyici bir motivasyon.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D3'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Meslek/kurum prestiji tercihlerinde önemli bir yer tutuyor.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D3'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Statü kaygısı senin için orta düzeyde, tek başına yönlendirici değil.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D3'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Toplumsal statü senin motivasyon haritanda düşük — yüksek prestijli ama senin ilgi alanınla örtüşmeyen alanlarda zorlanabilirsin.', 'Kararını statü yerine günlük iş içeriğine göre değerlendirmek daha isabetli olur.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'D3'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Statü/prestij senin için neredeyse hiç önemli değil — bu, toplumsal beklentiyle kendi tercihin arasında gerginlik yaratabilir.', 'Ailenden/çevrenden gelen ''prestijli meslek'' beklentisiyle kendi motivasyonun arasındaki farkı erken fark etmek, ileride pişmanlığı azaltır.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'D3'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'İşinin anlam taşıması senin için en güçlü motivasyon kaynaklarından biri.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D4'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Yaptığın işin bir amaca hizmet etmesi senin için önemli.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D4'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Anlam arayışın orta düzeyde, işin diğer yönleri de senin için belirleyici.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D4'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'İşin anlam taşıması senin için öncelikli değil — bu, yüksek ''misyon'' vurgusu yapan bölümlerde (öğretmenlik, sosyal hizmet gibi) motivasyon uyumsuzluğuna yol açabilir.', 'Hedef bölümün gerçek iş tanımını (günlük görevler) okuman, ''anlam'' söyleminin ötesinde neye katılacağını netleştirir.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'D4'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Anlam/amaç vurgusu senin kararlarında neredeyse hiç yer tutmuyor — ''misyon odaklı'' pazarlanan bölümlerin söylemine kapılmadan, somut iş içeriğine bakman önemli.', 'Bölüm tanıtımlarındaki idealist söylem yerine, mezunların gerçek iş günlerini araştırmak daha sağlıklı bir karar zemini sunar.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'D4'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Topluma somut fayda sağlamak senin için güçlü bir itici güç.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D5'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Sosyal etki yaratma isteğin kariyer tercihlerinde belirgin bir ağırlığa sahip.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D5'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Toplumsal katkı senin için orta düzeyde önemli.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D5'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Sosyal etki motivasyonun düşük — bu, ''topluma hizmet'' vurgusu yüksek mesleklerde (hekimlik, öğretmenlik) beklenti farkı yaratabilir.', 'Kısa süreli bir gönüllülük deneyimi, bu motivasyonun senin için gerçekten ne kadar önemli olduğunu netleştirebilir.', 'staj_deneyim', 'orta' FROM degiskenler WHERE kod = 'D5'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Toplumsal katkı senin motivasyon haritanda neredeyse hiç yer tutmuyor — bu bilinçli bir tercih olabilir, ama ''misyon'' vurgusu yüksek alanlarda hayal kırıklığı yaşamamak için göz önünde bulundur.', 'Kariyer kararını ''topluma katkı'' yerine kendi ilgi alanların üzerinden değerlendirmen daha tutarlı bir seçim sağlar.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'D5'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Kendi kararlarını verme ve esnek çalışma isteğin çok güçlü.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D6'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Özerklik/özgürlük senin için önemli bir çalışma tarzı tercihi.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D6'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Özerklik ihtiyacın orta düzeyde, hem bağımsız hem yapılandırılmış ortamlara açıksın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D6'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Özerklik ihtiyacın düşük — hiyerarşik, kuralları net kurumsal ortamlar seni rahatsız etmeyebilir, bu bir avantaj.', 'Hedef bölümün genellikle hangi tür kurumlara (büyük şirket, kamu, serbest) yönlendirdiğini araştırmak faydalı olur.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'D6'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Bağımsız çalışmaktan çok, net yönlendirme ve yapı içinde çalışmayı tercih ediyorsun — bu, girişimcilik ağırlıklı bölümlerde motivasyon uyumsuzluğu yaratabilir.', 'Kurumsal, hiyerarşik yapıya sahip meslek alanlarını araştırmak, çalışma tarzına daha uygun bir yol haritası çizer.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'D6'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Güzellik, tasarım ve özgün üretim senin için çok değerli.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D7'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Estetik ve yaratıcılık kariyer tercihlerinde belirgin bir yer tutuyor.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D7'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Estetik değer senin için orta düzeyde önemli.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'D7'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Estetik/yaratıcılık motivasyonun düşük — bu, tasarım ağırlıklı bölümlerde (mimarlık, grafik tasarım) uyum farkı yaratabilir.', 'Bir tasarım stüdyosu ya da atölye ziyareti, bu alanın günlük pratiğinin sana hitap edip etmediğini netleştirir.', 'staj_deneyim', 'orta' FROM degiskenler WHERE kod = 'D7'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Estetik kaygı senin kararlarında neredeyse hiç yer tutmuyor — görsel/yaratıcı üretim ağırlıklı alanlar muhtemelen seni tatmin etmeyecektir, bu değerli bir öz-farkındalık.', 'Kariyer arayışını daha analitik/işlevsel ağırlıklı alanlara yönlendirmen tutarlı olur.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'D7'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'İnsanlarla yüz yüze çalışmak, sosyal ortamdan enerji almak senin güçlü yanların.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P1'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Dışadönüklüğün belirgin — insan odaklı ortamlarda rahat hissediyorsun.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P1'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Sosyallik düzeyin dengeli — hem bireysel hem ekip çalışmasına açıksın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P1'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Daha içe dönük bir çalışma tarzın var — yoğun insan teması gerektiren rollerde enerjini hızlı tüketebilirsin.', 'Küçük grup sunumları veya proje takdimleriyle sosyal ortamlarda kademeli pratik yapmak faydalı olabilir.', 'aliskanlik', 'orta' FROM degiskenler WHERE kod = 'P1'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Belirgin şekilde içe dönüksün — sürekli insan teması gerektiren mesleklerde (satış, halkla ilişkiler) zorlanabilirsin.', 'Bağımsız/analitik ağırlıklı rollere yönelmek, enerjini koruyarak üretken olmanı sağlar.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'P1'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Empati ve uzlaşma konusunda çok güçlüsün, ekip uyumuna doğal katkı sağlıyorsun.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P2'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'İşbirliği eğilimin belirgin, ekip içinde uyum sağlama konusunda başarılısın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P2'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Uyumluluk düzeyin dengeli — hem işbirliğine hem gerektiğinde net durmaya açıksın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P2'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Çatışmadan kaçınma eğilimin düşük, kendi görüşünü net savunuyorsun — bu bir güç ama ekip ortamlarında sürtüşme yaratabilir.', 'Aktif dinleme pratiği yapmak, güçlü duruşunu koruyarak ekip uyumunu artırabilir.', 'aliskanlik', 'orta' FROM degiskenler WHERE kod = 'P2'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Uzlaşma/empati düzeyin belirgin şekilde düşük — yoğun ekip çalışması gerektiren ortamlarda bu net bir sürtüşme kaynağı olabilir.', 'Küçük ölçekli grup projelerinde bilinçli olarak dinleme ve uzlaşma pratiği yapmak faydalı olur.', 'proje', 'orta' FROM degiskenler WHERE kod = 'P2'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Planlı çalışma ve görev bilincin çok güçlü — güvenilir biri olarak öne çıkıyorsun.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P3'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Sorumluluk düzeyin belirgin, işleri zamanında tamamlama konusunda başarılısın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P3'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Disiplin düzeyin dengeli — bazen esnek, bazen planlı çalışıyorsun.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P3'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Planlama ve önceliklendirme konusunda zorlanabiliyorsun — bu, deadline ağırlıklı mesleklerde risk oluşturabilir.', 'Küçük projelerde kendi kendine son teslim tarihleri belirleyip bu ritme alışmak faydalı olabilir.', 'aliskanlik', 'orta' FROM degiskenler WHERE kod = 'P3'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Disiplin ve planlama belirgin şekilde zayıf bir alanın — yüksek sorumluluk gerektiren rollerde bu ciddi bir risk oluşturabilir.', 'Basit bir görev takip sistemi (liste, takvim) kullanmayı günlük alışkanlık haline getirmek iyi bir başlangıç noktası.', 'aliskanlik', 'uzun' FROM degiskenler WHERE kod = 'P3'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Duygusal hassasiyetin (stres/kaygıya karşı) diğer alanlara göre daha belirgin çıktı. [Bkz. dosya başındaki AÇIK SORU notu]', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P4'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Duygusal hassasiyetin ortalamanın biraz üzerinde. [Bkz. dosya başındaki AÇIK SORU notu]', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P4'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Duygusal hassasiyetin dengeli düzeyde.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P4'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Stres ve kaygıya karşı nispeten dirençlisin, duygusal iniş çıkışlar seni fazla etkilemiyor.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P4'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Duygusal olarak oldukça dengeli ve dirençlisin, yüksek baskı altında bile sakinliğini koruyabiliyorsun.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P4'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Yeni fikirlere ve değişime çok açıksın, merak dürtün güçlü.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P5'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Deneyime açıklığın belirgin, yeni alanlara ilgi duyuyorsun.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P5'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Yeniliğe açıklığın dengeli — hem bilindik hem yeni yaklaşımlara açıksın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P5'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Yeni fikirlere açıklığın düşük — hızlı değişen, belirsiz alanlarda konfor alanının dışına çıkman gerekebilir.', 'Bilmediğin bir konuda kısa bir okuma/kurs denemek, yeni bilgiye açıklığını kademeli artırabilir.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'P5'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Değişime açıklığın belirgin şekilde düşük — hızlı değişen sektörlerde (teknoloji, yaratıcı endüstriler) zorlanabilirsin.', 'Küçük, düşük riskli yeni deneyimlerle (yeni bir hobi, farklı bir ders) başlamak faydalı bir alışkanlık olur.', 'aliskanlik', 'uzun' FROM degiskenler WHERE kod = 'P5'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Değişken, sürprizli işlerden güçlü keyif alıyorsun, dinamik ortamlar seni motive ediyor.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P6'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Dinamik tercih belirgin, tekrarlayan işlerden çabuk sıkılabilirsin.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P6'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Rutin-dinamik dengede, ikisine de uyum sağlayabiliyorsun.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P6'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Rutine yatkınsın, öngörülebilir işler seni rahatsız etmiyor — hızlı değişen ortamlarda bunalabilirsin.', 'Değişkenlik içeren küçük görevlere (rotasyon, farklı projeler) gönüllü olmak esnekliğini artırabilir.', 'proje', 'orta' FROM degiskenler WHERE kod = 'P6'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Güçlü bir rutin tercihin var — sürekli değişen, öngörülemez ortamlar seni ciddi şekilde zorlayabilir.', 'Yapılandırılmış, öngörülebilir süreçleri olan alanlara yönelmek daha uyumlu bir seçim olur.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'P6'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Belirsizliğe ve riske toleransın çok yüksek, net olmayan durumlarda rahat hareket ediyorsun.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P7'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Risk toleransın belirgin, girişimci ortamlara uyum sağlayabilirsin.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P7'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Risk toleransın dengeli — hem güvenli hem belirsiz durumlara açıksın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P7'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Belirsizliğe toleransın düşük, net kurallar tercih ediyorsun — girişimcilik ağırlıklı alanlarda stres yaşayabilirsin.', 'Küçük, düşük riskli belirsiz durumları (yeni bir proje, tanımadığın bir görev) deneyimlemek toleransını kademeli artırabilir.', 'proje', 'orta' FROM degiskenler WHERE kod = 'P7'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Belirsizlik toleransın belirgin şekilde düşük — sonucu net olmayan, kuralsız ortamlar seni ciddi şekilde zorlayabilir.', 'Net süreçleri, tanımlı rolleri olan kurumsal/yapılandırılmış alanlara yönelmek daha uyumlu olur.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'P7'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Liderlik ve sorumluluk alma isteğin çok güçlü, karar verici pozisyonlara doğal ilgin var.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P8'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Yönetme isteğin belirgin, ekibe yön verme konusunda motivasyonlusun.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P8'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Liderlik isteğin orta düzeyde — hem yönetebilir hem takip edebilirsin.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'P8'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Liderlik/yönetme isteğin düşük — bu bir eksiklik değil, ama yönetim ağırlıklı kariyer yollarında motivasyon uyumsuzluğu yaratabilir.', 'Küçük ölçekli bir proje liderliği deneyimi, bu alanın sana gerçekten uyup uymadığını netleştirebilir.', 'proje', 'orta' FROM degiskenler WHERE kod = 'P8'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Yönetme/liderlik isteğin belirgin şekilde düşük — bu bilinçli bir tercih olabilir, uzman/bireysel katkı odaklı rollere yönelmek daha uyumlu olur.', 'Kariyer hedefini yönetim kademesi yerine derinlemesine uzmanlık gerektiren rollere göre şekillendirmek tutarlı olur.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'P8'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Zaman yönetimi ve önceliklendirme konusunda çok güçlüsün, yoğun tempoda bile düzenini koruyorsun.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I1'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Zaman yönetimin belirgin bir güçlü yanın, deadline''ları iyi yönetiyorsun.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I1'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Zaman yönetimi becerin ortalama düzeyde.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I1'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Planlama ve önceliklendirmede zorlanabiliyorsun — yoğun tempolu rollerde bu risk oluşturabilir.', 'Küçük projelerde kendine son teslim tarihleri belirleyip bu ritme alışmak faydalı olabilir.', 'aliskanlik', 'orta' FROM degiskenler WHERE kod = 'I1'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Zaman yönetimi belirgin bir gelişim alanın — birden fazla işi eşzamanlı yürütmen gereken rollerde ciddi bir zorluk yaşayabilirsin.', 'Basit bir planlama sistemi (haftalık liste, takvim bloklama) kullanmayı alışkanlık haline getirmek iyi bir başlangıç.', 'aliskanlik', 'uzun' FROM degiskenler WHERE kod = 'I1'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Takım içi anlaşmazlıkları çözme konusunda çok güçlüsün, farklı görüşleri yönetebiliyorsun.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I2'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Çatışma yönetimi belirgin bir güçlü yanın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I2'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Çatışma yönetimi becerin ortalama düzeyde.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I2'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Ekip içi anlaşmazlıklarda zorlanabiliyorsun — yoğun takım çalışması gerektiren rollerde bu gelişim alanı olabilir.', 'Grup projelerinde bilinçli olarak arabuluculuk/uzlaştırma rolü almayı denemek faydalı olur.', 'proje', 'orta' FROM degiskenler WHERE kod = 'I2'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Çatışma yönetimi belirgin bir gelişim alanın — bu, yoğun ekip koordinasyonu gerektiren rollerde önemli bir risk oluşturabilir.', 'Temel çatışma çözme/müzakere becerilerine dair kısa bir kurs almak somut bir başlangıç sağlar.', 'kurs', 'orta' FROM degiskenler WHERE kod = 'I2'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Stres altında, eksik bilgiyle bile makul kararlar verme konusunda çok güçlüsün.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I3'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Kriz anında karar verme belirgin bir güçlü yanın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I3'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Baskı altında karar verme becerin ortalama düzeyde.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I3'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Stres altında karar vermekte zorlanabiliyorsun — hızlı tempo/kriz yönetimi gerektiren rollerde bu gelişim alanı olabilir.', 'Zaman baskılı küçük simülasyon/vaka çalışmalarıyla pratik yapmak faydalı olabilir.', 'proje', 'orta' FROM degiskenler WHERE kod = 'I3'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Baskı altında karar verme belirgin bir gelişim alanın — acil karar gerektiren ortamlar (sağlık, acil müdahale) seni ciddi şekilde zorlayabilir.', 'Daha öngörülebilir, hazırlık süresi tanıyan iş ortamlarına yönelmek daha uyumlu bir seçim olabilir.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'I3'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Etik ilkelere bağlılığın çok güçlü, adalet ve dürüstlük senin için temel bir değer.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I4'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Etik duyarlılığın belirgin bir güçlü yanın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I4'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Etik duyarlılığın ortalama düzeyde.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I4'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Etik/dürüstlük duyarlılığın diğer alanlara göre daha düşük çıktı — bu bir zafiyet değil, ama yüksek etik sorumluluk gerektiren mesleklerde (hukuk, sağlık) üzerinde durmakta fayda var.', 'Hedef mesleğin etik kodlarını/vaka örneklerini incelemek farkındalığını artırabilir.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'I4'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Etik duyarlılık belirgin şekilde düşük çıktı — bu sonucu ciddiye alıp, yüksek etik sorumluluk taşıyan mesleklerde bu alanı geliştirmek önemli.', 'Meslek etiği üzerine temel bir kaynak okumak iyi bir başlangıç noktası olabilir.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'I4'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Beklemeden sorumluluk alma, proaktif davranma konusunda çok güçlüsün.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I5'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'İnisiyatif alma belirgin bir güçlü yanın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I5'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'İnisiyatif alma eğilimin ortalama düzeyde.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I5'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'İnisiyatif almakta zorlanabiliyorsun — yönlendirme beklemek yerine harekete geçmen gereken rollerde bu gelişim alanı olabilir.', 'Küçük, düşük riskli görevlerde önce sen adım atmayı bilinçli olarak denemek faydalı olur.', 'aliskanlik', 'orta' FROM degiskenler WHERE kod = 'I5'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'İnisiyatif alma belirgin bir gelişim alanın — yüksek özerklik ve proaktiflik gerektiren rollerde bu ciddi bir fark yaratabilir.', 'Net yönlendirme/hiyerarşi olan yapılandırılmış ortamlara yönelmek daha uyumlu bir başlangıç olabilir.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'I5'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Yapıcı eleştiriyi kabul etme, hatadan öğrenme konusunda çok güçlüsün.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I6'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Geri bildirime açıklığın belirgin bir güçlü yanın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I6'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Eleştiriye açıklığın ortalama düzeyde.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I6'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Geri bildirim almakta zorlanabiliyorsun — sürekli değerlendirme/geri bildirim döngüsü olan rollerde bu gelişim alanı olabilir.', 'Küçük geri bildirimleri savunmaya geçmeden dinleme pratiği yapmak faydalı olabilir.', 'aliskanlik', 'orta' FROM degiskenler WHERE kod = 'I6'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Eleştiriye açıklık belirgin bir gelişim alanın — yoğun performans değerlendirmesi olan ortamlarda bu zorlayıcı olabilir.', 'Güvendiğin biriyle düşük riskli geri bildirim alışverişi yapmayı düzenli bir alışkanlık haline getirmek iyi bir başlangıç.', 'aliskanlik', 'uzun' FROM degiskenler WHERE kod = 'I6'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Stratejik düşünme, süreç ve insan yönetimi konusunda çok güçlüsün.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I7'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Yönetim/strateji yetkinliğin belirgin bir güçlü yanın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I7'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Yönetim yetkinliğin ortalama düzeyde.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'I7'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Stratejik/yönetimsel düşünme senin için gelişmekte olan bir alan — yönetim ağırlıklı rollerde bunu geliştirmek faydalı olur.', 'Temel işletme/yönetim kavramlarına dair kısa bir kurs almak iyi bir başlangıç noktası.', 'kurs', 'orta' FROM degiskenler WHERE kod = 'I7'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Yönetim/strateji yetkinliği belirgin bir gelişim alanın — yoğun yönetimsel sorumluluk gerektiren rollerde bu önemli bir fark yaratabilir.', 'Küçük ölçekli bir proje veya kulüp yönetimi deneyimi, bu yetkinliği pratik yoluyla geliştirebilir.', 'proje', 'uzun' FROM degiskenler WHERE kod = 'I7'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Matematik, istatistik ve sistem mantığına çok güçlü bir yatkınlığın var.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A1'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Sayısal/veri odaklı düşünme belirgin bir güçlü yanın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A1'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Sayısal eğilimin ortalama düzeyde.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A1'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Sayısal/veri odaklı çalışma senin doğal eğilimlerinden biri değil — yoğun matematik/istatistik içeren bölümlerde bu bir zorluk yaratabilir.', 'Temel istatistik/veri analizi üzerine kısa bir kurs, bu alandaki rahatlığını artırabilir.', 'kurs', 'orta' FROM degiskenler WHERE kod = 'A1'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Sayısal eğilim belirgin şekilde düşük çıktı — yoğun matematik/mühendislik ağırlıklı bölümler seni zorlayabilir, bu bölüm seçiminde ciddiye alınmalı bir sinyal.', 'Hedef bölümün müfredatındaki sayısal derslerin yoğunluğunu incelemek gerçekçi bir beklenti oluşturur.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'A1'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Metin, dil ve kavramsal tartışma konularına çok güçlü bir ilgin var.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A2'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Sözel/dilsel düşünme belirgin bir güçlü yanın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A2'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Sözel eğilimin ortalama düzeyde.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A2'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Yoğun okuma-yazma ve kavramsal tartışma senin doğal ilgi alanın değil — sözel ağırlıklı bölümlerde bu bir zorluk yaratabilir.', 'Düzenli okuma/yazma pratiği (günlük tutmak, makale özetlemek) bu alandaki rahatlığını artırabilir.', 'aliskanlik', 'uzun' FROM degiskenler WHERE kod = 'A2'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Sözel eğilim belirgin şekilde düşük — yoğun metin/argüman ağırlıklı bölümler (hukuk, edebiyat) seni ciddi şekilde zorlayabilir.', 'Hedef bölümün ders içeriklerindeki okuma/yazma yükünü önceden araştırmak gerçekçi bir beklenti oluşturur.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'A2'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'İnsan davranışı, psikoloji ve insan merkezli alanlara çok güçlü bir ilgin var.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A3'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Sosyal/insan odaklı eğilim belirgin bir güçlü yanın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A3'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Sosyal eğilimin ortalama düzeyde.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A3'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'İnsan merkezli, ilişki yoğun alanlar senin doğal ilgi alanın değil — bu, sosyal hizmet/eğitim gibi bölümlerde göz önünde bulundurulmalı.', 'Kısa bir gönüllülük veya gözlem deneyimi, bu alanın sana uyup uymadığını netleştirebilir.', 'staj_deneyim', 'orta' FROM degiskenler WHERE kod = 'A3'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Sosyal/insan odaklı eğilim belirgin şekilde düşük — yoğun insan etkileşimi gerektiren bölümler seni tatmin etmeyebilir.', 'Daha bağımsız/teknik ağırlıklı alanları araştırmak daha uyumlu bir yön çizebilir.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'A3'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Görsel-estetik problem çözme ve tasarıma çok güçlü bir yatkınlığın var.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A4'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Yaratıcı/tasarım eğilimi belirgin bir güçlü yanın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A4'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Yaratıcı eğilimin ortalama düzeyde.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A4'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Görsel/tasarım odaklı üretim senin doğal ilgi alanın değil — tasarım ağırlıklı bölümlerde bu bir uyumsuzluk yaratabilir.', 'Bir tasarım atölyesi/dersini deneyimlemek bu alanın sana uygunluğunu netleştirebilir.', 'staj_deneyim', 'orta' FROM degiskenler WHERE kod = 'A4'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Yaratıcı/tasarım eğilimi belirgin şekilde düşük — yoğun görsel üretim gerektiren bölümler (mimarlık, grafik tasarım) seni zorlayabilir.', 'Daha analitik/yapılandırılmış alanları araştırmak daha uyumlu bir yön çizebilir.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'A4'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Biyoloji, kimya, saha ve laboratuvar çalışmalarına çok güçlü bir ilgin var.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A5'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Doğa/canlı odaklı eğilim belirgin bir güçlü yanın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A5'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Doğa/canlı eğilimin ortalama düzeyde.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A5'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Laboratuvar/saha çalışmaları senin doğal ilgi alanın değil — yoğun bu tür pratik içeren bölümlerde göz önünde bulundurulmalı.', 'Bir laboratuvar/saha gözlem deneyimi, bu alanın sana uyup uymadığını netleştirebilir.', 'staj_deneyim', 'orta' FROM degiskenler WHERE kod = 'A5'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Doğa/canlı eğilimi belirgin şekilde düşük — yoğun laboratuvar/saha çalışması gerektiren bölümler (biyoloji, veterinerlik) seni zorlayabilir.', 'Hedef bölümün pratik/laboratuvar yükünü önceden araştırmak gerçekçi bir beklenti oluşturur.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'A5'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Beden kullanımı, hareket ve sahada aktif olmaya çok güçlü bir yatkınlığın var.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A6'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Fiziksel/hareket eğilimi belirgin bir güçlü yanın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A6'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Fiziksel eğilimin ortalama düzeyde.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A6'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Fiziksel aktivite/hareket yoğun işler senin doğal tercihin değil — spor/beden odaklı bölümlerde bu göz önünde bulundurulmalı.', 'Hedef alanın fiziksel gereksinimlerini önceden araştırmak gerçekçi bir beklenti oluşturur.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'A6'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Fiziksel/hareket eğilimi belirgin şekilde düşük — yoğun fiziksel aktivite gerektiren bölümler (spor bilimleri, beden eğitimi) seni zorlayabilir.', 'Daha masa başı/analitik ağırlıklı alanları araştırmak daha uyumlu bir yön çizebilir.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'A6'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Kuralları net, aşamalı ve sistematik çalışma tarzın çok güçlü.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A7'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Yapılandırılmış çalışma tarzı belirgin bir güçlü yanın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A7'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Yapılandırılmış çalışma eğilimin ortalama düzeyde.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A7'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Net kurallar ve aşamalı süreçler senin doğal tarzın değil — yoğun prosedür/protokol gerektiren alanlarda bu bir uyum farkı yaratabilir.', 'Kısa süreli, adım adım ilerleyen bir görevi tamamlamayı bilinçli olarak denemek faydalı olabilir.', 'aliskanlik', 'orta' FROM degiskenler WHERE kod = 'A7'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Yapılandırılmış/sistematik çalışma tarzı belirgin şekilde zayıf — katı prosedürler içeren alanlar (mühendislik, sağlık) seni zorlayabilir.', 'Basit bir kontrol listesi/şablon kullanarak görevleri adım adım tamamlama alışkanlığı geliştirmek iyi bir başlangıç.', 'aliskanlik', 'uzun' FROM degiskenler WHERE kod = 'A7'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Büyük resmi görme, sezgiyle ilerleme konusunda çok güçlüsün.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A8'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Sezgisel/genel çerçeve düşüncesi belirgin bir güçlü yanın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A8'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Sezgisel düşünme eğilimin ortalama düzeyde.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A8'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Büyük resmi görüp sezgiyle ilerlemek senin doğal tarzın değil — daha soyut/kavramsal ağırlıklı alanlarda bu bir fark yaratabilir.', 'Karmaşık bir problemi detaylara girmeden önce genel hatlarıyla özetleme pratiği yapmak faydalı olabilir.', 'aliskanlik', 'orta' FROM degiskenler WHERE kod = 'A8'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Sezgisel/bütüncül düşünme belirgin şekilde zayıf bir alanın — yüksek soyutlama gerektiren alanlar (felsefe, teorik bilimler) seni zorlayabilir.', 'Daha somut, adım adım ilerleyen alanları araştırmak daha uyumlu bir yön çizebilir.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'A8'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_ustun', 'Fırsat görme, satış/pazarlık yapma ve risk alarak iş kurma isteğin çok güçlü.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A9'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'ustun', 'Girişimcilik/ikna eğilimi belirgin bir güçlü yanın.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A9'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'beklenti', 'Girişimcilik eğilimin ortalama düzeyde.', NULL, NULL, NULL FROM degiskenler WHERE kod = 'A9'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'altinda', 'Satış/pazarlık ve risk alarak iş kurma senin doğal eğilimin değil — girişimcilik ağırlıklı bölümlerde bu göz önünde bulundurulmalı.', 'Küçük bir satış/pazarlama deneyimi (bir etkinlik, ürün tanıtımı), bu alanın sana uyup uymadığını netleştirebilir.', 'proje', 'orta' FROM degiskenler WHERE kod = 'A9'""",
        r"""INSERT INTO gelisim_yorum_havuzu (degisken_id, aralik, durum_tespiti, aksiyon_onerisi, kaynak_tipi, tahmini_efor) SELECT id, 'belirgin_altinda', 'Girişimcilik/ikna eğilimi belirgin şekilde düşük — yoğun satış/pazarlık gerektiren roller seni zorlayabilir, bu bilinçli bir tercih olabilir.', 'Daha uzmanlık/teknik ağırlıklı, doğrudan satış gerektirmeyen alanları araştırmak daha uyumlu bir yön çizebilir.', 'okuma', 'kisa' FROM degiskenler WHERE kod = 'A9'""",
    ]
    for statement in _sql:
        op.execute(statement)


def downgrade():
    op.execute("DELETE FROM gelisim_yorum_havuzu")
