"""Gelişim karşılaştırma yorumu içeriği (F5.3) — 31 değişken × 5 trend = 155 satır

Revision ID: 0006_gelisim_karsilastirma_yorumu
Revises: 0005_p4_yon_duzeltmesi
Create Date: 2026-08-13
"""
from alembic import op

revision = "0006_gelisim_karsilastirma_yorumu"
down_revision = "0005_p4_yon_duzeltmesi"
branch_labels = None
depends_on = None


def upgrade():
    _sql = [
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Güvenceye verdiğin önem belirgin şekilde arttı — kararlarında istikrar ve öngörülebilirlik daha fazla yer tutmaya başladı.' FROM degiskenler WHERE kod = 'D1'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Güvenceye verdiğin önem bir miktar arttı.' FROM degiskenler WHERE kod = 'D1'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Güvenceye verdiğin önem geçen turdan bu yana pek değişmedi.' FROM degiskenler WHERE kod = 'D1'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Güvenceye verdiğin önem bir miktar azaldı, risk almaya biraz daha açık hale geldin.' FROM degiskenler WHERE kod = 'D1'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Güvenceye verdiğin önem belirgin şekilde azaldı — önceliklerinde önemli bir kayma var.' FROM degiskenler WHERE kod = 'D1'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Yüksek gelire verdiğin önem belirgin şekilde arttı.' FROM degiskenler WHERE kod = 'D2'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Ekonomik getiriye verdiğin önem bir miktar arttı.' FROM degiskenler WHERE kod = 'D2'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Ekonomik getiriye verdiğin önem değişmedi.' FROM degiskenler WHERE kod = 'D2'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Ekonomik getiriye verdiğin önem bir miktar azaldı, başka önceliklere kaydın.' FROM degiskenler WHERE kod = 'D2'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Ekonomik getiriye verdiğin önem belirgin şekilde azaldı.' FROM degiskenler WHERE kod = 'D2'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Statü/prestije verdiğin önem belirgin şekilde arttı.' FROM degiskenler WHERE kod = 'D3'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Statüye verdiğin önem bir miktar arttı.' FROM degiskenler WHERE kod = 'D3'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Statüye verdiğin önem değişmedi.' FROM degiskenler WHERE kod = 'D3'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Statüye verdiğin önem bir miktar azaldı.' FROM degiskenler WHERE kod = 'D3'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Statüye verdiğin önem belirgin şekilde azaldı — toplumsal tanınırlık artık kararlarında daha az belirleyici.' FROM degiskenler WHERE kod = 'D3'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'İşinin anlam taşımasına verdiğin önem belirgin şekilde arttı.' FROM degiskenler WHERE kod = 'D4'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Anlam arayışın bir miktar güçlendi.' FROM degiskenler WHERE kod = 'D4'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Anlam arayışın değişmedi.' FROM degiskenler WHERE kod = 'D4'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Anlam arayışın bir miktar azaldı.' FROM degiskenler WHERE kod = 'D4'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Anlam arayışın belirgin şekilde azaldı — işin pratik yönleri şu an senin için daha belirleyici.' FROM degiskenler WHERE kod = 'D4'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Topluma katkı motivasyonun belirgin şekilde arttı.' FROM degiskenler WHERE kod = 'D5'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Sosyal etki isteğin bir miktar arttı.' FROM degiskenler WHERE kod = 'D5'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Sosyal etki isteğin değişmedi.' FROM degiskenler WHERE kod = 'D5'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Sosyal etki isteğin bir miktar azaldı.' FROM degiskenler WHERE kod = 'D5'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Toplumsal katkı motivasyonun belirgin şekilde azaldı.' FROM degiskenler WHERE kod = 'D5'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Özerklik/özgürlük ihtiyacın belirgin şekilde arttı.' FROM degiskenler WHERE kod = 'D6'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Özerklik ihtiyacın bir miktar arttı.' FROM degiskenler WHERE kod = 'D6'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Özerklik ihtiyacın değişmedi.' FROM degiskenler WHERE kod = 'D6'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Özerklik ihtiyacın bir miktar azaldı, daha yapılandırılmış ortamlara açık hale geldin.' FROM degiskenler WHERE kod = 'D6'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Özerklik ihtiyacın belirgin şekilde azaldı.' FROM degiskenler WHERE kod = 'D6'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Estetik/yaratıcılık değerine verdiğin önem belirgin şekilde arttı.' FROM degiskenler WHERE kod = 'D7'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Estetik değer bir miktar önem kazandı.' FROM degiskenler WHERE kod = 'D7'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Estetik değere verdiğin önem değişmedi.' FROM degiskenler WHERE kod = 'D7'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Estetik değere verdiğin önem bir miktar azaldı.' FROM degiskenler WHERE kod = 'D7'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Estetik/yaratıcılık değeri belirgin şekilde önem kaybetti.' FROM degiskenler WHERE kod = 'D7'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Sosyal ortamlarda daha rahat hissetmeye başladığın belirgin şekilde görülüyor — dışadönüklüğün arttı.' FROM degiskenler WHERE kod = 'P1'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Dışadönüklüğün bir miktar arttı.' FROM degiskenler WHERE kod = 'P1'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Dışadönüklük düzeyin değişmedi.' FROM degiskenler WHERE kod = 'P1'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Dışadönüklüğün bir miktar azaldı, daha içe dönük bir eğilim gösteriyorsun.' FROM degiskenler WHERE kod = 'P1'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Dışadönüklüğün belirgin şekilde azaldı.' FROM degiskenler WHERE kod = 'P1'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Empati ve uzlaşma becerin belirgin şekilde gelişti.' FROM degiskenler WHERE kod = 'P2'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Uyumluluk/işbirliği eğilimin bir miktar gelişti.' FROM degiskenler WHERE kod = 'P2'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Uyumluluk düzeyin değişmedi.' FROM degiskenler WHERE kod = 'P2'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Uyumluluk/işbirliği eğilimin bir miktar azaldı.' FROM degiskenler WHERE kod = 'P2'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Uyumluluk düzeyin belirgin şekilde azaldı.' FROM degiskenler WHERE kod = 'P2'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Sorumluluk ve disiplin düzeyin belirgin şekilde gelişti.' FROM degiskenler WHERE kod = 'P3'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Sorumluluk düzeyin bir miktar gelişti.' FROM degiskenler WHERE kod = 'P3'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Sorumluluk düzeyin değişmedi.' FROM degiskenler WHERE kod = 'P3'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Sorumluluk düzeyin bir miktar azaldı.' FROM degiskenler WHERE kod = 'P3'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Sorumluluk/disiplin düzeyin belirgin şekilde azaldı — bu alana dikkat etmekte fayda var.' FROM degiskenler WHERE kod = 'P3'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Duygusal dengen belirgin şekilde arttı — stres ve baskı karşısında eskisine göre çok daha sakin kalabiliyorsun.' FROM degiskenler WHERE kod = 'P4'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Duygusal dengen bir miktar arttı, strese karşı biraz daha dirençli hale geldin.' FROM degiskenler WHERE kod = 'P4'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Duygusal hassasiyet düzeyin değişmedi.' FROM degiskenler WHERE kod = 'P4'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Duygusal hassasiyetin bir miktar arttı, stres seni eskisine göre biraz daha fazla etkiliyor.' FROM degiskenler WHERE kod = 'P4'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Duygusal hassasiyetin belirgin şekilde arttı — stres yönetimi konusuna dikkat etmekte fayda var.' FROM degiskenler WHERE kod = 'P4'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Yeniliğe açıklığın belirgin şekilde arttı.' FROM degiskenler WHERE kod = 'P5'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Deneyime açıklığın bir miktar arttı.' FROM degiskenler WHERE kod = 'P5'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Deneyime açıklığın değişmedi.' FROM degiskenler WHERE kod = 'P5'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Deneyime açıklığın bir miktar azaldı.' FROM degiskenler WHERE kod = 'P5'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Yeniliğe açıklığın belirgin şekilde azaldı.' FROM degiskenler WHERE kod = 'P5'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Dinamik/değişken ortamlara olan eğilimin belirgin şekilde arttı.' FROM degiskenler WHERE kod = 'P6'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Dinamik ortamlara eğilimin bir miktar arttı.' FROM degiskenler WHERE kod = 'P6'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Rutin-dinamik tercihin değişmedi.' FROM degiskenler WHERE kod = 'P6'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Rutine olan eğilimin bir miktar arttı, değişkenlikten biraz daha az keyif alır oldun.' FROM degiskenler WHERE kod = 'P6'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Rutine olan eğilimin belirgin şekilde arttı.' FROM degiskenler WHERE kod = 'P6'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Belirsizliğe ve riske toleransın belirgin şekilde arttı.' FROM degiskenler WHERE kod = 'P7'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Risk toleransın bir miktar arttı.' FROM degiskenler WHERE kod = 'P7'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Risk toleransın değişmedi.' FROM degiskenler WHERE kod = 'P7'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Risk toleransın bir miktar azaldı, net ve öngörülebilir durumları daha çok tercih eder oldun.' FROM degiskenler WHERE kod = 'P7'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Belirsizliğe toleransın belirgin şekilde azaldı.' FROM degiskenler WHERE kod = 'P7'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Liderlik/yönetme isteğin belirgin şekilde arttı.' FROM degiskenler WHERE kod = 'P8'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Yönetme isteğin bir miktar arttı.' FROM degiskenler WHERE kod = 'P8'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Liderlik isteğin değişmedi.' FROM degiskenler WHERE kod = 'P8'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Yönetme isteğin bir miktar azaldı.' FROM degiskenler WHERE kod = 'P8'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Liderlik/yönetme isteğin belirgin şekilde azaldı.' FROM degiskenler WHERE kod = 'P8'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Zaman yönetimi ve önceliklendirme becerin belirgin şekilde gelişti.' FROM degiskenler WHERE kod = 'I1'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Zaman yönetimi becerin bir miktar gelişti.' FROM degiskenler WHERE kod = 'I1'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Zaman yönetimi becerin değişmedi.' FROM degiskenler WHERE kod = 'I1'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Zaman yönetimi becerin bir miktar geriledi.' FROM degiskenler WHERE kod = 'I1'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Zaman yönetimi becerin belirgin şekilde geriledi — bu alana odaklanmakta fayda var.' FROM degiskenler WHERE kod = 'I1'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Çatışma yönetimi becerin belirgin şekilde gelişti.' FROM degiskenler WHERE kod = 'I2'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Ekip/çatışma yönetimi becerin bir miktar gelişti.' FROM degiskenler WHERE kod = 'I2'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Çatışma yönetimi becerin değişmedi.' FROM degiskenler WHERE kod = 'I2'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Çatışma yönetimi becerin bir miktar geriledi.' FROM degiskenler WHERE kod = 'I2'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Ekip/çatışma yönetimi becerin belirgin şekilde geriledi.' FROM degiskenler WHERE kod = 'I2'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Baskı altında karar verme becerin belirgin şekilde gelişti.' FROM degiskenler WHERE kod = 'I3'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Kriz anında karar verme becerin bir miktar gelişti.' FROM degiskenler WHERE kod = 'I3'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Baskı altında karar verme becerin değişmedi.' FROM degiskenler WHERE kod = 'I3'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Baskı altında karar verme becerin bir miktar geriledi.' FROM degiskenler WHERE kod = 'I3'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Kriz anında karar verme becerin belirgin şekilde geriledi.' FROM degiskenler WHERE kod = 'I3'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Etik/dürüstlük duyarlılığın belirgin şekilde arttı.' FROM degiskenler WHERE kod = 'I4'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Etik duyarlılığın bir miktar arttı.' FROM degiskenler WHERE kod = 'I4'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Etik duyarlılığın değişmedi.' FROM degiskenler WHERE kod = 'I4'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Etik duyarlılığın bir miktar azaldı.' FROM degiskenler WHERE kod = 'I4'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Etik/dürüstlük duyarlılığın belirgin şekilde azaldı — bu sonucu ciddiye almakta fayda var.' FROM degiskenler WHERE kod = 'I4'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'İnisiyatif alma becerin belirgin şekilde gelişti.' FROM degiskenler WHERE kod = 'I5'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'İnisiyatif alma eğilimin bir miktar gelişti.' FROM degiskenler WHERE kod = 'I5'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'İnisiyatif alma eğilimin değişmedi.' FROM degiskenler WHERE kod = 'I5'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'İnisiyatif alma eğilimin bir miktar geriledi.' FROM degiskenler WHERE kod = 'I5'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'İnisiyatif alma becerin belirgin şekilde geriledi.' FROM degiskenler WHERE kod = 'I5'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Geri bildirime açıklığın belirgin şekilde gelişti.' FROM degiskenler WHERE kod = 'I6'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Eleştiriye açıklığın bir miktar gelişti.' FROM degiskenler WHERE kod = 'I6'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Geri bildirime açıklığın değişmedi.' FROM degiskenler WHERE kod = 'I6'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Geri bildirime açıklığın bir miktar geriledi.' FROM degiskenler WHERE kod = 'I6'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Eleştiriye açıklığın belirgin şekilde geriledi.' FROM degiskenler WHERE kod = 'I6'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Yönetim/strateji yetkinliğin belirgin şekilde gelişti.' FROM degiskenler WHERE kod = 'I7'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Stratejik düşünme yetkinliğin bir miktar gelişti.' FROM degiskenler WHERE kod = 'I7'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Yönetim yetkinliğin değişmedi.' FROM degiskenler WHERE kod = 'I7'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Yönetim/strateji yetkinliğin bir miktar geriledi.' FROM degiskenler WHERE kod = 'I7'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Yönetim yetkinliğin belirgin şekilde geriledi.' FROM degiskenler WHERE kod = 'I7'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Sayısal/veri odaklı düşünme eğilimin belirgin şekilde gelişti.' FROM degiskenler WHERE kod = 'A1'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Sayısal eğilimin bir miktar gelişti.' FROM degiskenler WHERE kod = 'A1'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Sayısal eğilimin değişmedi.' FROM degiskenler WHERE kod = 'A1'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Sayısal eğilimin bir miktar geriledi.' FROM degiskenler WHERE kod = 'A1'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Sayısal/veri odaklı eğilimin belirgin şekilde geriledi.' FROM degiskenler WHERE kod = 'A1'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Sözel/dilsel eğilimin belirgin şekilde gelişti.' FROM degiskenler WHERE kod = 'A2'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Sözel eğilimin bir miktar gelişti.' FROM degiskenler WHERE kod = 'A2'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Sözel eğilimin değişmedi.' FROM degiskenler WHERE kod = 'A2'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Sözel eğilimin bir miktar geriledi.' FROM degiskenler WHERE kod = 'A2'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Sözel/dilsel eğilimin belirgin şekilde geriledi.' FROM degiskenler WHERE kod = 'A2'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Sosyal/insan odaklı eğilimin belirgin şekilde gelişti.' FROM degiskenler WHERE kod = 'A3'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Sosyal eğilimin bir miktar gelişti.' FROM degiskenler WHERE kod = 'A3'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Sosyal eğilimin değişmedi.' FROM degiskenler WHERE kod = 'A3'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Sosyal eğilimin bir miktar geriledi.' FROM degiskenler WHERE kod = 'A3'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Sosyal/insan odaklı eğilimin belirgin şekilde geriledi.' FROM degiskenler WHERE kod = 'A3'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Yaratıcı/tasarım eğilimin belirgin şekilde gelişti.' FROM degiskenler WHERE kod = 'A4'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Yaratıcı eğilimin bir miktar gelişti.' FROM degiskenler WHERE kod = 'A4'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Yaratıcı eğilimin değişmedi.' FROM degiskenler WHERE kod = 'A4'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Yaratıcı eğilimin bir miktar geriledi.' FROM degiskenler WHERE kod = 'A4'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Yaratıcı/tasarım eğilimin belirgin şekilde geriledi.' FROM degiskenler WHERE kod = 'A4'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Doğa/canlı odaklı eğilimin belirgin şekilde gelişti.' FROM degiskenler WHERE kod = 'A5'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Doğa/canlı eğilimin bir miktar gelişti.' FROM degiskenler WHERE kod = 'A5'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Doğa/canlı eğilimin değişmedi.' FROM degiskenler WHERE kod = 'A5'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Doğa/canlı eğilimin bir miktar geriledi.' FROM degiskenler WHERE kod = 'A5'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Doğa/canlı odaklı eğilimin belirgin şekilde geriledi.' FROM degiskenler WHERE kod = 'A5'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Fiziksel/hareket eğilimin belirgin şekilde gelişti.' FROM degiskenler WHERE kod = 'A6'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Fiziksel eğilimin bir miktar gelişti.' FROM degiskenler WHERE kod = 'A6'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Fiziksel eğilimin değişmedi.' FROM degiskenler WHERE kod = 'A6'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Fiziksel eğilimin bir miktar geriledi.' FROM degiskenler WHERE kod = 'A6'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Fiziksel/hareket eğilimin belirgin şekilde geriledi.' FROM degiskenler WHERE kod = 'A6'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Yapılandırılmış/adım adım çalışma tarzın belirgin şekilde güçlendi.' FROM degiskenler WHERE kod = 'A7'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Yapılandırılmış çalışma eğilimin bir miktar arttı.' FROM degiskenler WHERE kod = 'A7'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Çalışma tarzın (yapılandırılmış-sezgisel) değişmedi.' FROM degiskenler WHERE kod = 'A7'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Yapılandırılmış çalışma eğilimin bir miktar azaldı, daha sezgisel bir tarza kaydın.' FROM degiskenler WHERE kod = 'A7'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Adım adım/yapılandırılmış çalışma tarzın belirgin şekilde azaldı.' FROM degiskenler WHERE kod = 'A7'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Sezgisel/genel çerçeve düşünme eğilimin belirgin şekilde arttı.' FROM degiskenler WHERE kod = 'A8'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Sezgisel düşünme eğilimin bir miktar arttı.' FROM degiskenler WHERE kod = 'A8'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Sezgisel düşünme eğilimin değişmedi.' FROM degiskenler WHERE kod = 'A8'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Sezgisel düşünme eğilimin bir miktar azaldı, daha adım adım bir tarza kaydın.' FROM degiskenler WHERE kod = 'A8'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Sezgisel/genel çerçeve düşünme eğilimin belirgin şekilde azaldı.' FROM degiskenler WHERE kod = 'A8'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gelisim', 'Girişimcilik/pazarlama eğilimin belirgin şekilde gelişti.' FROM degiskenler WHERE kod = 'A9'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gelisim', 'Girişimcilik eğilimin bir miktar gelişti.' FROM degiskenler WHERE kod = 'A9'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'durgun', 'Girişimcilik eğilimin değişmedi.' FROM degiskenler WHERE kod = 'A9'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'gerileme', 'Girişimcilik eğilimin bir miktar geriledi.' FROM degiskenler WHERE kod = 'A9'""",
        r"""INSERT INTO gelisim_karsilastirma_yorumu (degisken_id, trend, yorum_metni) SELECT id, 'belirgin_gerileme', 'Girişimcilik/pazarlama eğilimin belirgin şekilde geriledi.' FROM degiskenler WHERE kod = 'A9'""",
    ]
    for statement in _sql:
        op.execute(statement)


def downgrade():
    op.execute("DELETE FROM gelisim_karsilastirma_yorumu")
