"""301 bölümün kısa açıklaması (D5 Katman 2 — Keşfet için)

Revision ID: 0007_bolum_aciklamalari
Revises: 0006_gelisim_karsilastirma_yorumu
Create Date: 2026-08-13

Kaynak: Bölüm_Listesi.xlsx. 301 bölüm adıyla birebir (karakter
karakter) eşleştiği otomatik olarak doğrulandı.
"""
from alembic import op

revision = "0007_bolum_aciklamalari"
down_revision = "0006_gelisim_karsilastirma_yorumu"
branch_labels = None
depends_on = None


def upgrade():
    _sql = [
        r"""UPDATE bolumler SET kisa_aciklama = 'Ekonomik olayları matematiksel ve istatistiksel modellerle analiz eder, tahmin yöntemleri geliştirir.' WHERE ad = 'EKONOMETRİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Doğal afetler ve acil durumlara müdahale, risk azaltma ve kriz yönetimi planlaması öğretir.' WHERE ad = 'ACİL YARDIM VE AFET YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Suç mahallinden elde edilen kanıtları bilimsel yöntemlerle inceleyip adalete katkı sağlar.' WHERE ad = 'ADLİ BİLİMLER'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Dijital cihazlardaki kanıtları tespit edip analiz ederek siber suçların aydınlatılmasına katkı sağlar.' WHERE ad = 'ADLİ BİLİŞİM MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Ahşap malzemenin işlenmesi, mobilya ve orman ürünleri üretim süreçlerini tasarlar.' WHERE ad = 'AĞAÇ İŞLERİ ENDÜSTRİ MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Aile yapısı, tüketici davranışı ve ev ekonomisi konularında bilimsel yaklaşımlar geliştirir.' WHERE ad = 'AİLE VE TÜKETİCİ BİLİMLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Çanta, ayakkabı, takı gibi moda aksesuarlarının tasarım ve üretim süreçlerini kapsar.' WHERE ad = 'AKSESUAR TASARIMI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Sigorta ve emeklilik sistemlerindeki riskleri istatistik ve olasılık teorisiyle hesaplar.' WHERE ad = 'AKTÜERYA BİLİMLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Dijital animasyon içerikleri ve video oyunlarının tasarım, kurgu ve üretim sürecini öğretir.' WHERE ad = 'ANİMASYON VE OYUN TASARIMI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Sporcuların performansını geliştirmek için antrenman bilimi ve spor pedagojisi üzerine eğitim verir.' WHERE ad = 'ANTRENÖRLÜK EĞİTİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'İnsan toplulukları, kültürleri ve biyolojik çeşitliliği karşılaştırmalı olarak inceler.' WHERE ad = 'ANTROPOLOJİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Geçmiş uygarlıklardan kalan maddi kalıntıları kazı ve analiz yöntemleriyle araştırır.' WHERE ad = 'ARKEOLOJİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Gök cisimlerini, evrenin yapısını ve uzay olaylarını gözlem ve teorik yöntemlerle inceler.' WHERE ad = 'ASTRONOMİ VE UZAY BİLİMLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'AB''nin kurumsal yapısı, hukuku ve Türkiye ile ilişkilerini çok yönlü ele alır.' WHERE ad = 'AVRUPA BİRLİĞİ İLİŞKİLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Ayakkabı tasarımı, model geliştirme ve üretim tekniklerini uygulamalı olarak öğretir.' WHERE ad = 'AYAKKABI TASARIMI VE ÜRETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Meyve, sebze ve süs bitkilerinin yetiştirilmesi, ıslahı ve hasat sonrası işlenmesini kapsar.' WHERE ad = 'BAHÇE BİTKİLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Su ürünleri avcılığı, işleme ve sürdürülebilir balıkçılık yönetimini mühendislik yaklaşımıyla ele alır.' WHERE ad = 'BALIKÇILIK TEKNOLOJİSİ MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Bankacılık sistemleri, finansal piyasalar ve kurumsal finans yönetimi üzerine uzmanlaşır.' WHERE ad = 'BANKACILIK VE FİNANS'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Banka ve sigorta sektörlerinin işleyişini, ürünlerini ve risk yönetimini öğretir.' WHERE ad = 'BANKACILIK VE SİGORTACILIK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Baskı, matbaacılık ve dijital yayıncılık teknolojilerinin üretim süreçlerini kapsar.' WHERE ad = 'BASIM TEKNOLOJİLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Gazetecilik, haber üretimi ve medya sektörünün işleyişini uygulamalı olarak öğretir.' WHERE ad = 'BASIN VE YAYIN'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Gravür, litografi gibi geleneksel ve çağdaş baskı tekniklerini sanatsal üretimle birleştirir.' WHERE ad = 'BASKI SANATLARI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'İnsan beslenmesi, hastalıklara özel diyet planlaması ve toplum beslenmesi konularında uzmanlaşır.' WHERE ad = 'BESLENME VE DİYETETİK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Müzik eseri besteleme teknikleri ve orkestra yönetimi becerilerini bir arada geliştirir.' WHERE ad = 'BESTECİLİK VE ORKESTRA ŞEFLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Farklı sanat disiplinlerini (görsel, sahne, ses) bir arada ele alan disiplinlerarası bir programdır.' WHERE ad = 'BİLEŞİK SANATLAR'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Bilgi sistemlerini siber saldırılara karşı koruma, güvenlik mimarisi tasarlama üzerine uzmanlaşır.' WHERE ad = 'BİLGİ GÜVENLİĞİ MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Kütüphane, arşiv ve bilgi merkezlerinin düzenlenmesi ve yönetimi üzerine eğitim verir.' WHERE ad = 'BİLGİ VE BELGE YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Algoritmalar, hesaplama teorisi ve yazılım sistemlerinin teorik temellerini inceler.' WHERE ad = 'BİLGİSAYAR BİLİMLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Donanım ve yazılım sistemlerinin tasarımı, geliştirilmesi ve entegrasyonunu kapsar.' WHERE ad = 'BİLGİSAYAR MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Eğitimde teknoloji kullanımı ve bilişim öğretmenliği için pedagojik formasyon sağlar.' WHERE ad = 'BİLGİSAYAR VE ÖĞRETİM TEKNOLOJİLERİ ÖĞRETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Bilimsel düşüncenin ve keşiflerin tarihsel gelişimini felsefi bir bakışla inceler.' WHERE ad = 'BİLİM TARİHİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Kurumsal bilgi sistemlerinin tasarımı, entegrasyonu ve yönetimini mühendislik yaklaşımıyla ele alır.' WHERE ad = 'BİLİŞİM SİSTEMLERİ MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Bitki hastalıkları, zararlılar ve yabancı otlarla mücadele yöntemlerini bilimsel temelde öğretir.' WHERE ad = 'BİTKİ KORUMA'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tarımsal üretim süreçlerini modern teknolojilerle birleştirerek verimliliği artırmayı hedefler.' WHERE ad = 'BİTKİSEL ÜRETİM VE TEKNOLOJİLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Canlı organizmalardaki kimyasal süreçleri ve molekül yapılarını inceler.' WHERE ad = 'BİYOKİMYA'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Canlıların yapısı, işlevi, çeşitliliği ve evrimini geniş bir yelpazede araştırır.' WHERE ad = 'BİYOLOJİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Biyoloji alanında hem bilimsel bilgi hem pedagojik formasyon kazandırır.' WHERE ad = 'BİYOLOJİ ÖĞRETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tıbbi cihaz ve teknolojilerin tasarımı için mühendislik ve tıp bilgisini birleştirir.' WHERE ad = 'BİYOMEDİKAL MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Biyolojik sistemleri mühendislik prensipleriyle birleştirerek yeni teknolojiler geliştirir.' WHERE ad = 'BİYOMÜHENDİSLİK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tarımsal ve biyolojik üretim sistemlerini mühendislik çözümleriyle optimize eder.' WHERE ad = 'BİYOSİSTEM MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Canlı sistemleri kullanarak endüstriyel, tarımsal ve tıbbi ürünler geliştirir.' WHERE ad = 'BİYOTEKNOLOJİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Cam sanatı ve tasarımını atölye ortamında uygulamalı olarak öğretir.' WHERE ad = 'CAM'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Caz ve popüler müzik türlerinde icra, beste ve düzenleme becerilerini geliştirir.' WHERE ad = 'CAZ VE POPÜLER MÜZİK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Madenden çıkarılan cevherlerin zenginleştirilmesi ve işlenmesi süreçlerini kapsar.' WHERE ad = 'CEVHER HAZIRLAMA MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Yeryüzünün fiziki ve beşeri özelliklerini, mekansal ilişkileri bilimsel olarak inceler.' WHERE ad = 'COĞRAFYA'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Coğrafya alan bilgisiyle birlikte öğretmenlik formasyonu kazandırır.' WHERE ad = 'COĞRAFYA ÖĞRETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Müzik aletlerinin yapımı, bakımı ve akustik özelliklerini teknik olarak öğretir.' WHERE ad = 'ÇALGI TEKNOLOJİLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'İşgücü piyasası, endüstri ilişkileri ve sosyal politika konularında uzmanlaşır.' WHERE ad = 'ÇALIŞMA EKONOMİSİ VE ENDÜSTRİ İLİŞKİLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Hava, su, toprak kirliliğinin önlenmesi ve çevresel sürdürülebilirlik çözümleri geliştirir.' WHERE ad = 'ÇEVRE MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Geleneksel çini sanatının tasarım, üretim ve restorasyon tekniklerini öğretir.' WHERE ad = 'ÇİNİ TASARIMI VE ONARIMI'""",
        r"""UPDATE bolumler SET kisa_aciklama = '2B/3B animasyon üretimi ve çizgi film yapım tekniklerini uygulamalı olarak öğretir.' WHERE ad = 'ÇİZGİ FİLM VE ANİMASYON'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Erken çocukluk döneminde bilişsel, sosyal ve duygusal gelişimi destekleyecek uzmanlık kazandırır.' WHERE ad = 'ÇOCUK GELİŞİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Gemi işletmeciliği ve deniz taşımacılığı yönetimini mühendislik temelinde ele alır.' WHERE ad = 'DENİZ ULAŞTIRMA İŞLETME MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Liman, gemi işletmeciliği ve denizcilik sektörünün yönetim süreçlerini kapsar.' WHERE ad = 'DENİZCİLİK İŞLETMELERİ YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Deri işleme teknolojileri ve deri ürünleri üretim süreçlerini mühendislik yaklaşımıyla ele alır.' WHERE ad = 'DERİ MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Dijital platformlarda pazarlama stratejileri ve içerik üretimini bir arada öğretir.' WHERE ad = 'DİJİTAL MEDYA VE PAZARLAMA'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Video oyunu tasarımı, oyun mekaniği ve kullanıcı deneyimi üzerine uzmanlaşır.' WHERE ad = 'DİJİTAL OYUN TASARIMI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Bir yabancı dilin öğretimi için hem dil hem pedagoji bilgisi kazandırır.' WHERE ad = 'DİL ÖĞRETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Bir dilin yapısını ve o dildeki edebi eserleri karşılaştırmalı olarak inceler.' WHERE ad = 'DİL VE EDEBİYAT'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Konuşma, dil ve yutma bozukluklarının tanı ve tedavisi üzerine uzmanlaşır.' WHERE ad = 'DİL VE KONUŞMA TERAPİSİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Ağız ve diş sağlığının korunması, hastalıkların teşhis ve tedavisini kapsayan klinik bir alandır.' WHERE ad = 'DİŞ HEKİMLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Ekosistemlerin korunması ve biyolojik çeşitliliğin sürdürülebilir yönetimini ele alır.' WHERE ad = 'DOĞA KORUMA VE BİYOÇEŞİTLİLİK YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Sahne oyunculuğu teknikleri ve drama eğitimini uygulamalı olarak öğretir.' WHERE ad = 'DRAMA VE OYUNCULUK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Oyun metni yazarlığı ve dramaturji analizini bir arada geliştirir.' WHERE ad = 'DRAMA YAZARLIĞI VE DRAMATURJİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Gebelik, doğum ve lohusalık dönemlerinde anne-bebek sağlığını takip eden klinik bir meslektir.' WHERE ad = 'EBELİK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'İlaçların geliştirilmesi, üretimi, analizi ve güvenli kullanımı üzerine uzmanlaşan sağlık alanıdır.' WHERE ad = 'ECZACILIK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Fiziksel aktivitenin insan sağlığı ve performansı üzerindeki etkilerini bilimsel olarak inceler.' WHERE ad = 'EGZERSİZ VE SPOR BİLİMLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Kaynakların üretimi, dağılımı ve tüketimini teorik ve uygulamalı olarak analiz eder.' WHERE ad = 'EKONOMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Ekonomi teorisiyle finansal piyasa analizini bir arada ele alır.' WHERE ad = 'EKONOMİ VE FİNANS'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Geleneksel el sanatları tekniklerini atölye ortamında uygulamalı olarak öğretir.' WHERE ad = 'EL SANATLARI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Elektrik enerjisi sistemleri ve elektronik devre tasarımını kapsayan geniş bir mühendislik dalıdır.' WHERE ad = 'ELEKTRİK VE ELEKTRONİK MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Online ticaret platformları ve dijital işletme yönetimi üzerine uzmanlaşır.' WHERE ad = 'ELEKTRONİK TİCARET VE YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Üretim ve hizmet sistemlerini optimize ederek verimliliği artıracak çözümler tasarlar.' WHERE ad = 'ENDÜSTRİ MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Günlük kullanım ürünlerinin işlevsel ve estetik tasarımını gerçekleştirir.' WHERE ad = 'ENDÜSTRİYEL TASARIM'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Ürün tasarımını mühendislik bilgisiyle birleştirerek üretilebilir tasarımlar geliştirir.' WHERE ad = 'ENDÜSTRİYEL TASARIM MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Yenilenebilir ve konvansiyonel enerji sistemlerinin tasarımı ve yönetimini kapsar.' WHERE ad = 'ENERJİ SİSTEMLERİ MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Enerji kaynaklarının verimli kullanımı ve enerji politikalarını yönetim perspektifiyle ele alır.' WHERE ad = 'ENERJİ YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Günlük yaşam becerilerini kaybetmiş bireylerin bağımsızlığını yeniden kazanmasına yardımcı olan rehabilitasyon alanıdır.' WHERE ad = 'ERGOTERAPİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Varlık, bilgi, değer gibi temel sorular üzerine eleştirel ve sistematik düşünme geliştirir.' WHERE ad = 'FELSEFE'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Felsefe, psikoloji, sosyoloji gibi derslerin öğretmenliği için formasyon kazandırır.' WHERE ad = 'FELSEFE GRUBU ÖĞRETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Ortaokul düzeyinde fen bilimleri öğretimi için alan ve pedagoji bilgisi kazandırır.' WHERE ad = 'FEN BİLGİSİ ÖĞRETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Senaryo yazarlığı ve film anlatısının tasarım sürecini bir arada öğretir.' WHERE ad = 'FİLM TASARIMI VE YAZARLIĞI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Film yapımının görsel tasarımı ve yönetmenlik becerilerini geliştirir.' WHERE ad = 'FİLM TASARIMI VE YÖNETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Film prodüksiyon süreçleri ve dağıtım/yayıncılık boyutunu bir arada ele alır.' WHERE ad = 'FİLM YAPIMI VE YAYINCILIK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Finansal yönetim ve bankacılık uygulamalarını bir arada uzmanlık alanı olarak sunar.' WHERE ad = 'FİNANS VE BANKACILIK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Maddenin ve enerjinin temel yasalarını deneysel ve teorik yöntemlerle araştırır.' WHERE ad = 'FİZİK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Fizik biliminin mühendislik problemlerine uygulanmasını sağlayan disiplinlerarası bir alandır.' WHERE ad = 'FİZİK MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Fizik alan bilgisiyle birlikte lise düzeyinde öğretmenlik formasyonu kazandırır.' WHERE ad = 'FİZİK ÖĞRETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Hareket sistemi bozukluklarının tedavisi ve fiziksel rehabilitasyon üzerine uzmanlaşan klinik alandır.' WHERE ad = 'FİZYOTERAPİ VE REHABİLİTASYON'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Fotoğraf ve video prodüksiyonunun teknik ve sanatsal yönlerini öğretir.' WHERE ad = 'FOTOĞRAF VE VİDEO'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Işığın üretimi, kontrolü ve algılanmasına dayalı teknolojileri inceleyen bir mühendislik dalıdır.' WHERE ad = 'FOTONİK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Mutfak sanatları, yemek kültürü ve gastronomi işletmeciliğini bir arada öğretir.' WHERE ad = 'GASTRONOMİ VE MUTFAK SANATLARI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Gayrimenkul projelerinin geliştirilmesi, değerlemesi ve yönetimini kapsar.' WHERE ad = 'GAYRİMENKUL GELİŞTİRME VE YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Haber toplama, yazma ve medya üretim süreçlerini uygulamalı olarak öğretir.' WHERE ad = 'GAZETECİLİK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Hat, tezhip, ebru gibi geleneksel sanat formlarını atölye ortamında öğretir.' WHERE ad = 'GELENEKSEL TÜRK SANATLARI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Gemi tasarımı, inşası ve gemi makinelerinin mühendislik süreçlerini kapsar.' WHERE ad = 'GEMİ İNŞAATI VE GEMİ MAKİNELERİ MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Gemi makine sistemlerinin işletilmesi ve bakımını mühendislik temelinde ele alır.' WHERE ad = 'GEMİ MAKİNELERİ İŞLETME MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Gemi ve yat tasarımının teknik ve estetik yönlerini bir arada öğretir.' WHERE ad = 'GEMİ VE YAT TASARIMI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Genetik bilgiyi mühendislik yöntemleriyle birleştirerek biyoteknolojik uygulamalar geliştirir.' WHERE ad = 'GENETİK VE BİYOMÜHENDİSLİK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Yaşlanma sürecini biyolojik, psikolojik ve sosyal boyutlarıyla inceleyen bir bilim dalıdır.' WHERE ad = 'GERONTOLOJİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Gıda üretimi, işlenmesi, güvenliği ve muhafazası süreçlerini mühendislik yaklaşımıyla ele alır.' WHERE ad = 'GIDA MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Yeni iş fikirlerinin geliştirilmesi ve işletmeye dönüştürülmesi sürecini öğretir.' WHERE ad = 'GİRİŞİMCİLİK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Marka, reklam ve dijital medya için görsel tasarım çözümleri üretir.' WHERE ad = 'GÖRSEL İLETİŞİM TASARIMI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Resim, heykel gibi görsel sanat disiplinlerinde yaratıcı üretim becerisi kazandırır.' WHERE ad = 'GÖRSEL SANATLAR'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Görsel sanatlar alan bilgisiyle birlikte öğretmenlik formasyonu kazandırır.' WHERE ad = 'GÖRSEL SANATLAR ÖĞRETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Görsel iletişim için tipografi, imaj ve düzen tasarımını öğretir.' WHERE ad = 'GRAFİK TASARIMI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Gümrük mevzuatı ve dış ticaret işlemlerinin yönetimini uygulamalı olarak öğretir.' WHERE ad = 'GÜMRÜK İŞLETME'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Gemi yönetimi ve seyir güvenliği konularında denizcilik eğitimi verir.' WHERE ad = 'GÜVERTE'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Geleneksel ve çağdaş halı desenlerinin tasarım sürecini öğretir.' WHERE ad = 'HALI TASARIMI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Geleneksel dokuma sanatlarının desen tasarımı ve üretim tekniklerini kapsar.' WHERE ad = 'HALI, KİLİM VE GELENEKSEL KUMAŞ DESENLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Halk kültürü, gelenek ve folklorik üretimi bilimsel yöntemlerle inceler.' WHERE ad = 'HALKBİLİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Kurumsal iletişim, itibar yönetimi ve reklam kampanyası tasarımını öğretir.' WHERE ad = 'HALKLA İLİŞKİLER VE REKLAMCILIK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Arazi ölçümü, harita üretimi ve coğrafi bilgi sistemlerini mühendislik temelinde ele alır.' WHERE ad = 'HARİTA MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tarımda otomasyon, sensör teknolojileri ve robotik uygulamaları öğretir.' WHERE ad = 'HASSAS TARIM VE TARIMSAL ROBOTLAR'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Geleneksel İslam hat sanatının teknik ve estetik eğitimini verir.' WHERE ad = 'HAT SANATI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Hava sahasındaki uçuş trafiğinin güvenli yönetimi için teknik eğitim verir.' WHERE ad = 'HAVA TRAFİK KONTROLÜ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Uçaklardaki elektrik ve elektronik sistemlerin bakım ve onarımını öğretir.' WHERE ad = 'HAVACILIK ELEKTRİK VE ELEKTRONİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Uçak ve uzay araçlarının tasarımı, üretimi ve performansını inceleyen mühendislik dalıdır.' WHERE ad = 'HAVACILIK VE UZAY MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Havayolu işletmeciliği ve havacılık sektörünün yönetim süreçlerini kapsar.' WHERE ad = 'HAVACILIK YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Hayvancılık üretim sistemlerini modern teknolojilerle birleştirir.' WHERE ad = 'HAYVANSAL ÜRETİM VE TEKNOLOJİLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Hasta bakımı, sağlığın korunması ve tedavi sürecinde klinik hemşirelik becerisi kazandırır.' WHERE ad = 'HEMŞİRELİK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Üç boyutlu sanat eserlerinin tasarım ve üretim tekniklerini öğretir.' WHERE ad = 'HEYKEL'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Yeraltı su kaynaklarının araştırılması ve yönetimini mühendislik temelinde ele alır.' WHERE ad = 'HİDROJEOLOJİ MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Su kaynaklarının yönetimi ve hidrolik sistemlerin tasarımını kapsar.' WHERE ad = 'HİDROLİK VE SU KAYNAKLARI MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Yasaların yorumlanması, uygulanması ve adalet sisteminin işleyişini kapsamlı olarak öğretir.' WHERE ad = 'HUKUK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'İç mekanların işlevsel ve estetik tasarımını öğretir.' WHERE ad = 'İÇ MİMARLIK VE ÇEVRE TASARIMI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Hava olaylarının ve iklim değişikliğinin bilimsel analizini mühendislik yaklaşımıyla ele alır.' WHERE ad = 'İKLİM BİLİMİ VE METEOROLOJİ MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Ekonomik sistemlerin işleyişini, üretim ve tüketim ilişkilerini teorik olarak inceler.' WHERE ad = 'İKTİSAT'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'İslam dini, tarihi ve düşüncesini akademik yöntemlerle araştırır.' WHERE ad = 'İLAHİYAT'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Kitle iletişimi, medya ve iletişim süreçlerini kuramsal olarak inceler.' WHERE ad = 'İLETİŞİM BİLİMLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'İletişim stratejilerinin tasarımı ve yönetim süreçlerini bir arada ele alır.' WHERE ad = 'İLETİŞİM TASARIMI VE YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Ortaokul düzeyinde matematik öğretimi için alan ve pedagoji bilgisi kazandırır.' WHERE ad = 'İLKÖĞRETİM MATEMATİK ÖĞRETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Üretim süreçlerinin tasarımı ve optimizasyonunu mühendislik yaklaşımıyla ele alır.' WHERE ad = 'İMALAT MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Kurumlarda işe alım, performans ve personel gelişimi süreçlerini yönetir.' WHERE ad = 'İNSAN KAYNAKLARI YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Bina, köprü, yol gibi yapıların tasarımı ve inşasını kapsayan mühendislik dalıdır.' WHERE ad = 'İNŞAAT MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'İslam dini, hukuku ve tarihini akademik derinlikte inceler.' WHERE ad = 'İSLAM BİLİMLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'İslami finans prensipleri ve faizsiz bankacılık sistemlerini öğretir.' WHERE ad = 'İSLAM İKTİSADI VE FİNANS'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Veri toplama, analiz etme ve yorumlama yöntemlerini matematiksel temelde öğretir.' WHERE ad = 'İSTATİSTİK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Çalışma ortamındaki risklerin tespiti ve iş kazalarının önlenmesini kapsar.' WHERE ad = 'İŞ SAĞLIĞI VE GÜVENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Kurumların yönetimi, pazarlama, finans ve organizasyon süreçlerini geniş bir çerçevede öğretir.' WHERE ad = 'İŞLETME'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'İşletme yönetimi bilgisini mühendislik yaklaşımıyla birleştirir.' WHERE ad = 'İŞLETME MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Yerkabuğunun fiziksel özelliklerini inceleyerek maden ve enerji kaynaklarının aranmasına katkı sağlar.' WHERE ad = 'JEOFİZİK MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Yerkabuğunun yapısını, kayaçları ve yeraltı kaynaklarını mühendislik temelinde araştırır.' WHERE ad = 'JEOLOJİ MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Devlet kurumlarının yönetimi, kamu politikaları ve idare hukukunu öğretir.' WHERE ad = 'KAMU YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tavukçuluk ve diğer kanatlı hayvan üretim sistemlerini bilimsel temelde ele alır.' WHERE ad = 'KANATLI HAYVAN YETİŞTİRİCİLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Farklı dillerdeki edebi eserleri karşılaştırmalı yöntemlerle analiz eder.' WHERE ad = 'KARŞILAŞTIRMALI EDEBİYAT'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Kent mekanlarının ve açık alanların tasarımını bir arada ele alır.' WHERE ad = 'KENTSEL TASARIM VE PEYZAJ MİMARLIĞI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Maddenin yapısı, özellikleri ve kimyasal tepkimelerini deneysel yöntemlerle araştırır.' WHERE ad = 'KİMYA'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Kimyasal süreçlerin endüstriyel ölçekte tasarımı ve üretimini kapsar.' WHERE ad = 'KİMYA MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Kimya alan bilgisiyle birlikte lise düzeyinde öğretmenlik formasyonu kazandırır.' WHERE ad = 'KİMYA ÖĞRETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Kimya ve biyoloji mühendisliğini birleştiren disiplinlerarası bir programdır.' WHERE ad = 'KİMYA-BİYOLOJİ MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Endüstriyel sistemlerin otomatik kontrolü ve robotik uygulamalarını kapsar.' WHERE ad = 'KONTROL VE OTOMASYON MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Film ve video prodüksiyonunda kurgu, ses ve görüntü tekniklerini öğretir.' WHERE ad = 'KURGU, SES VE GÖRÜNTÜ YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Takı ve mücevher tasarımı, üretimi ve işleme tekniklerini öğretir.' WHERE ad = 'KUYUMCULUK VE MÜCEVHER TASARIMI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tarihi eserlerin restorasyonu ve korunması için teknik bilgi kazandırır.' WHERE ad = 'KÜLTÜR VARLIKLARINI KORUMA VE ONARIM'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Kültürel süreçler ve iletişim olgusunu disiplinlerarası bir yaklaşımla inceler.' WHERE ad = 'KÜLTÜR VE İLETİŞİM BİLİMLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Küresel siyasi dinamikleri ve devletlerarası ilişkileri analiz eder.' WHERE ad = 'KÜRESEL SİYASET VE ULUSLARARASI İLİŞKİLER'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Örgütsel liderlik teorileri ve yönetim becerilerini geliştirmeye odaklanır.' WHERE ad = 'LİDERLİK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tedarik zinciri ve lojistik süreçlerinin yönetimini öğretir.' WHERE ad = 'LOJİSTİK YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Yeraltı ve yerüstü maden kaynaklarının çıkarılması ve işlenmesini kapsar.' WHERE ad = 'MADEN MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Mekanik sistemlerin tasarımı, üretimi ve enerji dönüşümünü kapsayan temel bir mühendislik dalıdır.' WHERE ad = 'MAKİNE MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Kamu maliyesi, vergi sistemi ve bütçe yönetimini öğretir.' WHERE ad = 'MALİYE'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Malzemelerin yapısı, özellikleri ve yeni malzeme geliştirme süreçlerini inceler.' WHERE ad = 'MALZEME BİLİMİ VE MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Malzeme bilimini nano ölçekte uygulamalarla birleştirir.' WHERE ad = 'MALZEME BİLİMİ VE NANOTEKNOLOJİ MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Sayılar, yapılar ve soyut ilişkileri titiz bir mantıksal çerçevede araştırır.' WHERE ad = 'MATEMATİK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Matematiksel yöntemleri mühendislik problemlerinin çözümüne uygular.' WHERE ad = 'MATEMATİK MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Matematik alan bilgisiyle birlikte lise düzeyinde öğretmenlik formasyonu kazandırır.' WHERE ad = 'MATEMATİK ÖĞRETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Matematiksel teoriyi bilgisayar bilimi uygulamalarıyla birleştirir.' WHERE ad = 'MATEMATİK VE BİLGİSAYAR BİLİMLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Medya sektörünün yapısını ve iletişim süreçlerini kapsamlı olarak inceler.' WHERE ad = 'MEDYA VE İLETİŞİM'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Mekanik, elektronik ve yazılımı birleştirerek akıllı sistemler tasarlar.' WHERE ad = 'MEKATRONİK MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Metal üretim süreçleri ve malzeme özelliklerini mühendislik temelinde ele alır.' WHERE ad = 'METALURJİ VE MALZEME MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Bina ve mekanların işlevsel, estetik ve yapısal tasarımını kapsar.' WHERE ad = 'MİMARLIK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Giysi tasarımı, koleksiyon geliştirme ve moda endüstrisi süreçlerini öğretir.' WHERE ad = 'MODA TASARIMI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Çağdaş dans teknikleri ve koreografi becerilerini uygulamalı olarak geliştirir.' WHERE ad = 'MODERN DANS'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Hücresel ve moleküler düzeyde genetik mekanizmaları araştırır.' WHERE ad = 'MOLEKÜLER BİYOLOJİ VE GENETİK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Moleküler biyoloji bilgisini biyoteknolojik uygulamalara dönüştürür.' WHERE ad = 'MOLEKÜLER BİYOTEKNOLOJİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Finansal kayıtların tutulması ve denetim süreçlerini öğretir.' WHERE ad = 'MUHASEBE VE DENETİM'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Muhasebe uygulamalarını finansal yönetim bilgisiyle birleştirir.' WHERE ad = 'MUHASEBE VE FİNANS YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Yazılı ve sözlü çeviri becerilerini profesyonel düzeyde geliştirir.' WHERE ad = 'MÜTERCİM VE TERCÜMANLIK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Müze yönetimi, koleksiyon koruma ve sergileme tekniklerini öğretir.' WHERE ad = 'MÜZECİLİK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Müzik teorisi, icra ve besteleme üzerine kapsamlı bir eğitim sunar.' WHERE ad = 'MÜZİK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Belirli bir müzik aletinde ileri düzey icra becerisi kazandırır.' WHERE ad = 'MÜZİK ÇALGI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Müzik alan bilgisiyle birlikte öğretmenlik formasyonu kazandırır.' WHERE ad = 'MÜZİK ÖĞRETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Vokal teknikleri ve sahne performansı üzerine uzmanlaşır.' WHERE ad = 'MÜZİK SES VE PERFORMANS'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Ses kayıt, prodüksiyon ve müzik yazılımlarını teknik olarak öğretir.' WHERE ad = 'MÜZİK TEKNOLOJİSİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Müziğin yapısal ve teorik ilkelerini akademik düzeyde inceler.' WHERE ad = 'MÜZİK TEORİSİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Müziği tarihsel, kültürel ve analitik açılardan bilimsel olarak araştırır.' WHERE ad = 'MÜZİKOLOJİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Nano ölçekteki malzeme ve sistemleri disiplinlerarası bir yaklaşımla inceler.' WHERE ad = 'NANOBİLİM VE NANOTEKNOLOJİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Nano ölçekli malzeme ve cihazların mühendislik tasarımını kapsar.' WHERE ad = 'NANOTEKNOLOJİ MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Nükleer reaktör tasarımı ve nükleer enerji üretim süreçlerini öğretir.' WHERE ad = 'NÜKLEER ENERJİ MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'İşitme kayıpları ve denge bozukluklarının tanı ve rehabilitasyonu üzerine uzmanlaşır.' WHERE ad = 'ODYOLOJİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Erken çocukluk eğitimi için pedagojik formasyon kazandırır.' WHERE ad = 'OKUL ÖNCESİ ÖĞRETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Işık ve ses fiziğinin mühendislik uygulamalarını kapsar.' WHERE ad = 'OPTİK VE AKUSTİK MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Kimyasal girdisiz, sürdürülebilir tarım işletmeciliği ilkelerini öğretir.' WHERE ad = 'ORGANİK TARIM İŞLETMECİLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Orkestra ve koro yönetimi tekniklerini uygulamalı olarak geliştirir.' WHERE ad = 'ORKESTRA VE KORO ŞEFLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Orman ürünlerinin işlenmesi ve endüstriyel kullanımını mühendislik temelinde ele alır.' WHERE ad = 'ORMAN ENDÜSTRİSİ MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Orman ekosistemlerinin yönetimi ve sürdürülebilir orman kaynaklarını kapsar.' WHERE ad = 'ORMAN MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Yapay uzuv ve destekleyici cihazların tasarımı ve uygulanmasını öğretir.' WHERE ad = 'ORTEZ VE PROTEZ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Konaklama işletmelerinin operasyonel ve stratejik yönetimini öğretir.' WHERE ad = 'OTEL YÖNETİCİLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Motorlu taşıtların tasarımı, üretimi ve performansını mühendislik temelinde ele alır.' WHERE ad = 'OTOMOTİV MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Sahne ve ekran oyunculuğu tekniklerini uygulamalı olarak geliştirir.' WHERE ad = 'OYUNCULUK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Özel gereksinimli bireylerin eğitimi için uzmanlaşmış pedagojik formasyon sağlar.' WHERE ad = 'ÖZEL EĞİTİM ÖĞRETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Ürün ve hizmetlerin pazara sunulması, tüketici davranışı ve marka yönetimini öğretir.' WHERE ad = 'PAZARLAMA'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Pazarlama stratejilerini iletişim ve reklam teknikleriyle birleştirir.' WHERE ad = 'PAZARLAMA İLETİŞİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Kalp ve damar cerrahisinde yapay dolaşım sistemlerinin yönetimini öğreten klinik bir alandır.' WHERE ad = 'PERFÜZYON'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Petrol ve doğalgaz rezervlerinin aranması, çıkarılması ve işlenmesini kapsar.' WHERE ad = 'PETROL VE DOĞALGAZ MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Açık alan ve yeşil alan tasarımını ekolojik prensiplerle birleştirir.' WHERE ad = 'PEYZAJ MİMARLIĞI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Uçak kullanma ve hava taşımacılığı için teknik pilotluk eğitimi verir.' WHERE ad = 'PİLOTAJ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Resim ve diğer plastik sanat disiplinlerinde yaratıcı üretim becerisi kazandırır.' WHERE ad = 'PLASTİK SANATLAR VE RESİM'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Plastik ve polimer malzemelerin üretim ve işleme süreçlerini kapsar.' WHERE ad = 'POLİMER MALZEME MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Siyasi süreçlerle ekonomik politikaların etkileşimini disiplinlerarası olarak inceler.' WHERE ad = 'POLİTİKA VE EKONOMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'İnsan davranışı, zihinsel süreçler ve duygu durumlarını bilimsel yöntemlerle araştırır.' WHERE ad = 'PSİKOLOJİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Okullarda rehberlik ve psikolojik danışmanlık hizmeti verecek uzmanlar yetiştirir.' WHERE ad = 'PSİKOLOJİK DANIŞMANLIK VE REHBERLİK ÖĞRETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Yayıncılık, film yapımı ve medya prodüksiyonunu bir arada öğretir.' WHERE ad = 'RADYO, TELEVİZYON VE SİNEMA'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tren ve metro gibi raylı ulaşım sistemlerinin mühendislik tasarımını kapsar.' WHERE ad = 'RAYLI SİSTEMLER MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Bireylere psikolojik destek ve rehberlik hizmeti verecek uzmanlık kazandırır.' WHERE ad = 'REHBERLİK VE PSİKOLOJİK DANIŞMANLIK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Reklam kampanyalarının tasarımı, stratejisi ve üretim sürecini öğretir.' WHERE ad = 'REKLAMCILIK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Boş zaman etkinliklerinin planlanması ve yönetimini kapsar.' WHERE ad = 'REKREASYON YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Resim sanatında teknik beceri ve yaratıcı ifade geliştirir.' WHERE ad = 'RESİM'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Resim alan bilgisiyle birlikte öğretmenlik formasyonu kazandırır.' WHERE ad = 'RESİM ÖĞRETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Kuaförlük ve güzellik hizmetleri alanında teknik beceri kazandırır.' WHERE ad = 'SAÇ VE GÜZELLİK UYGULAMALARI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Hastane ve sağlık kurumlarının işletme ve yönetim süreçlerini öğretir.' WHERE ad = 'SAĞLIK YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tiyatro ve gösteri sanatları için dekor ve kostüm tasarımını öğretir.' WHERE ad = 'SAHNE DEKORU VE KOSTÜMÜ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tiyatro, dans ve performans sanatlarını disiplinlerarası bir yaklaşımla kapsar.' WHERE ad = 'SAHNE SANATLARI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tiyatro ve performans mekanlarının sahne tasarımını öğretir.' WHERE ad = 'SAHNE TASARIMI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Performans sanatları etkinliklerinin prodüksiyon ve yönetim süreçlerini kapsar.' WHERE ad = 'SAHNE VE GÖSTERİ SANATLARI YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Sanat eserlerini tarihsel ve kültürel bağlamda akademik olarak inceler.' WHERE ad = 'SANAT TARİHİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Kültür-sanat kurumlarının ve etkinliklerinin yönetimini öğretir.' WHERE ad = 'SANAT VE KÜLTÜR YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Seramik ve cam sanatının tasarım ve üretim tekniklerini öğretir.' WHERE ad = 'SERAMİK VE CAM'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Menkul kıymetler, borsa işlemleri ve yatırım araçlarını öğretir.' WHERE ad = 'SERMAYE PİYASASI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Ses tasarımı ve prodüksiyonunu sanatsal bir disiplin olarak ele alır.' WHERE ad = 'SES SANATLARI TASARIMI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Seyahat acenteciliği ve turist rehberliği hizmetlerini öğretir.' WHERE ad = 'SEYAHAT İŞLETMECİLİĞİ VE TURİZM REHBERLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'İlkokul düzeyinde çok alanlı öğretmenlik formasyonu kazandırır.' WHERE ad = 'SINIF ÖĞRETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Bilgi sistemlerini siber tehditlere karşı koruma tekniklerini mühendislik temelinde öğretir.' WHERE ad = 'SİBER GÜVENLİK MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Sigortacılık uygulamalarını risk hesaplama ve aktüerya bilimiyle birleştirir.' WHERE ad = 'SİGORTACILIK VE AKTÜERYA BİLİMLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Sigorta sektörü ve kurumsal risk yönetimi süreçlerini öğretir.' WHERE ad = 'SİGORTACILIK VE RİSK YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Film yapımını dijital medya prodüksiyon teknikleriyle birleştirir.' WHERE ad = 'SİNEMA VE DİJİTAL MEDYA'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Havayolu işletmeciliği ve sivil havacılık operasyonlarını öğretir.' WHERE ad = 'SİVİL HAVA ULAŞTIRMA İŞLETMECİLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Siyasi kurumları ve kamu yönetimi süreçlerini bir arada inceler.' WHERE ad = 'SİYASET BİLİMİ VE KAMU YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'İç ve dış siyaset dinamiklerini karşılaştırmalı olarak analiz eder.' WHERE ad = 'SİYASET BİLİMİ VE ULUSLARARASI İLİŞKİLER'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tarih, coğrafya ve vatandaşlık derslerinin ortaokul öğretmenliğini kapsar.' WHERE ad = 'SOSYAL BİLGİLER ÖĞRETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Toplumsal sorunların çözümü ve dezavantajlı gruplara destek sağlama üzerine uzmanlaşır.' WHERE ad = 'SOSYAL HİZMET'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Toplumsal yapılar, ilişkiler ve değişim süreçlerini bilimsel olarak inceler.' WHERE ad = 'SOSYOLOJİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Beden eğitimi ve spor alanında öğretmenlik formasyonu kazandırır.' WHERE ad = 'SPOR ÖĞRETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Spor kulüpleri ve organizasyonlarının yönetim süreçlerini öğretir.' WHERE ad = 'SPOR YÖNETİCİLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Su kaynaklarının yönetimi ve su mühendisliği uygulamalarını kapsar.' WHERE ad = 'SU BİLİMLERİ VE MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Balıkçılık ve su ürünleri yetiştiriciliğini mühendislik temelinde ele alır.' WHERE ad = 'SU ÜRÜNLERİ MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Süt ve süt ürünlerinin işlenmesi ve kalite kontrolünü öğretir.' WHERE ad = 'SÜT TEKNOLOJİSİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Kentlerin ve bölgelerin fiziksel, sosyal ve ekonomik planlamasını yapar.' WHERE ad = 'ŞEHİR VE BÖLGE PLANLAMA'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Takı tasarımı ve kuyumculuk üretim tekniklerini öğretir.' WHERE ad = 'TAKI TASARIMI VE İMALATI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tarımsal üretim ve piyasaların ekonomik analizini yapar.' WHERE ad = 'TARIM EKONOMİSİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tarımda kullanılan makine ve teknolojilerin mühendislik tasarımını kapsar.' WHERE ad = 'TARIM MAKİNELERİ VE TEKNOLOJİLERİ MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tarımsal ürünlerin ticareti ve işletme süreçlerini öğretir.' WHERE ad = 'TARIM TİCARETİ VE İŞLETMECİLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Biyoteknolojik yöntemleri tarımsal üretime uygulayarak verimliliği artırır.' WHERE ad = 'TARIMSAL BİYOTEKNOLOJİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Bitki ve hayvan genetiğini tarımsal ıslah amacıyla mühendislik yaklaşımıyla ele alır.' WHERE ad = 'TARIMSAL GENETİK MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tarımsal tesislerin tasarımı ve sulama sistemlerini mühendislik temelinde ele alır.' WHERE ad = 'TARIMSAL YAPILAR VE SULAMA'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Geçmiş olayları, toplumları ve süreçleri kaynaklara dayalı olarak araştırır.' WHERE ad = 'TARİH'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tarih alan bilgisiyle birlikte öğretmenlik formasyonu kazandırır.' WHERE ad = 'TARİH ÖĞRETMENLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Buğday, mısır gibi tarla ürünlerinin yetiştirilmesi ve ıslahını kapsar.' WHERE ad = 'TARLA BİTKİLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Teknoloji tabanlı iş fikirlerinin geliştirilmesi ve girişime dönüştürülmesini öğretir.' WHERE ad = 'TEKNOLOJİ GİRİŞİMCİLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tekstil malzemelerinin üretimi ve işlenmesini mühendislik temelinde ele alır.' WHERE ad = 'TEKSTİL MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Kumaş deseni ve tekstil ürünlerinin tasarım sürecini öğretir.' WHERE ad = 'TEKSTİL TASARIMI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tekstil üretimini moda tasarımı bilgisiyle birleştirir.' WHERE ad = 'TEKSTİL VE MODA TASARIMI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Televizyon haber üretimi ve program yapımcılığını öğretir.' WHERE ad = 'TELEVİZYON HABERCİLİĞİ VE PROGRAMCILIĞI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Geleneksel Türk süsleme sanatlarının teknik ve estetik eğitimini verir.' WHERE ad = 'TEZHİP-MİNYATÜR VE EBRU'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'İnsan sağlığının korunması, hastalıkların teşhis ve tedavisini kapsayan temel bir sağlık bilimidir.' WHERE ad = 'TIP'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tıbbi teknolojilerin geliştirilmesini mühendislik ve tıp bilgisiyle birleştirir.' WHERE ad = 'TIP MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Sahne sanatları, oyunculuk ve tiyatro yapımını kapsamlı olarak öğretir.' WHERE ad = 'TİYATRO'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tiyatro eserlerinin analitik değerlendirmesi ve dramaturji çalışmasını öğretir.' WHERE ad = 'TİYATRO ELEŞTİRMENLİĞİ VE DRAMATURJİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Tohum üretimi, kalitesi ve teknolojilerini bilimsel temelde ele alır.' WHERE ad = 'TOHUM BİLİMİ VE TEKNOLOJİSİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Toprak verimliliği ve bitki beslenmesi ilişkisini araştırır.' WHERE ad = 'TOPRAK BİLİMİ VE BİTKİ BESLEME'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Turizm sektöründeki işletmelerin yönetim süreçlerini öğretir.' WHERE ad = 'TURİZM İŞLETMECİLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Turistlere rehberlik hizmeti verecek profesyonelleri yetiştirir.' WHERE ad = 'TURİZM REHBERLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Turizm ve otelcilik işletmelerinin yönetimini bir arada öğretir.' WHERE ad = 'TURİZM VE KONAKLAMA İŞLETMECİLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Geleneksel Türk halk danslarının icra ve öğretimini kapsar.' WHERE ad = 'TÜRK HALK OYUNLARI'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Türk halk kültürü ve folklorunu akademik yöntemlerle araştırır.' WHERE ad = 'TÜRK HALKBİLİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Uçakların teknik bakım ve onarım süreçlerini uygulamalı olarak öğretir.' WHERE ad = 'UÇAK BAKIM VE ONARIM'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Uçakların aerodinamik tasarımı ve performansını mühendislik temelinde ele alır.' WHERE ad = 'UÇAK MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Ulaşım sistemlerinin planlanması ve trafik yönetimini kapsar.' WHERE ad = 'ULAŞTIRMA VE TRAFİK MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Ülkeler arası ekonomik etkileşimleri ve ticaret politikalarını inceler.' WHERE ad = 'ULUSLARARASI EKONOMİK İLİŞKİLER'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Küresel finansal piyasalar ve uluslararası yatırım süreçlerini öğretir.' WHERE ad = 'ULUSLARARASI FİNANS'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Küresel pazarlarda girişimcilik fırsatlarını değerlendirme becerisi kazandırır.' WHERE ad = 'ULUSLARARASI GİRİŞİMCİLİK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Devletler arası hukuki ilişkileri ve uluslararası anlaşmaları inceler.' WHERE ad = 'ULUSLARARASI HUKUK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Devletler arası siyasi, ekonomik ve diplomatik ilişkileri analiz eder.' WHERE ad = 'ULUSLARARASI İLİŞKİLER'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Küresel işletme yönetimi ve uluslararası ticaret süreçlerini öğretir.' WHERE ad = 'ULUSLARARASI İŞLETMECİLİK VE TİCARET'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Dış ticaret işlemleri ve uluslararası lojistik yönetimini kapsar.' WHERE ad = 'ULUSLARARASI TİCARET VE LOJİSTİK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Uzay araştırmaları ve uzay teknolojilerinin gelişimini inceler.' WHERE ad = 'UZAY BİLİMLERİ VE TEKNOLOJİLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Uzay araçları ve sistemlerinin mühendislik tasarımını kapsar.' WHERE ad = 'UZAY MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Büyük veri setlerinden anlamlı bilgi çıkarma yöntemlerini öğretir.' WHERE ad = 'VERİ BİLİMİ VE ANALİTİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Hayvan sağlığının korunması, hastalıkların teşhis ve tedavisini kapsayan klinik bir alandır.' WHERE ad = 'VETERİNERLİK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Yaban hayatı popülasyonlarının korunması ve yönetimini bilimsel temelde ele alır.' WHERE ad = 'YABAN HAYATI EKOLOJİSİ VE YÖNETİMİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Akıllı sistemlerin tasarımı ve makine öğrenmesi algoritmalarını geliştirir.' WHERE ad = 'YAPAY ZEKA MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Veriden öğrenen algoritma ve modellerin geliştirilmesini kapsar.' WHERE ad = 'YAPAY ZEKA VE MAKİNE ÖĞRENMESİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Yapay zeka sistemlerini veri mühendisliği altyapısıyla birleştirir.' WHERE ad = 'YAPAY ZEKA VE VERİ MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Yazılım sistemlerinin tasarımı, geliştirilmesi ve test süreçlerini kapsar.' WHERE ad = 'YAZILIM MÜHENDİSLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Dijital platformlarda haber üretimi ve yeni medya araçlarını öğretir.' WHERE ad = 'YENİ MEDYA VE GAZETECİLİK'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Dijital iletişim teknolojileri ve yeni medya kuramlarını inceler.' WHERE ad = 'YENİ MEDYA VE İLETİŞİM'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Belediyeler ve yerel yönetim birimlerinin işleyişini öğretir.' WHERE ad = 'YEREL YÖNETİMLER'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Restoran ve catering işletmelerinin yönetim süreçlerini kapsar.' WHERE ad = 'YİYECEK VE İÇECEK İŞLETMECİLİĞİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'İşletme yönetimini bilgi teknolojileri altyapısıyla birleştirir.' WHERE ad = 'YÖNETİM BİLİŞİM SİSTEMLERİ'""",
        r"""UPDATE bolumler SET kisa_aciklama = 'Evcil hayvanların yetiştirilmesi, ıslahı ve verimliliğini bilimsel temelde ele alır.' WHERE ad = 'ZOOTEKNİ'""",
    ]
    for statement in _sql:
        op.execute(statement)


def downgrade():
    op.execute("UPDATE bolumler SET kisa_aciklama = NULL")
