"""03.10.2026'da Supabase'de elle yapılan değişikliklerin kayıt altına alınması

Revision ID: 0008_ekim_duzeltmeleri
Revises: 0007_bolum_aciklamalari
Create Date: 2026-10-03

Bu değişiklikler canlı veritabanına zaten SQL Editor'den uygulandı. Bu migration
yalnızca kayıt ve yeni kurulumların aynı duruma gelmesi içindir; tüm adımlar
tekrar çalıştırılmaya dayanıklıdır (idempotent) — canlıda çalıştırılsa da zarar vermez.

1) bolum_agirliklari: agirlikli_varyans 99.99 sınırına takılıyordu (varyans 351'e çıkabiliyor)
2) meslekler: ESCO kaynağına izin; eski çakışan kısıt kaldırıldı
3) Katman ağırlıkları: K4 (Alan Eğilimi) %40, K1-K3 %20
4) K5 parametreleri: eşik 70, en fazla 2 dal
5) Dal - K4 değişkeni bağlantıları
6) Bölüm - dal eşleşmeleri (301 bölüm, elle gözden geçirilmiş)
"""
from alembic import op

revision = "0008_ekim_duzeltmeleri"
down_revision = "0007_bolum_aciklamalari"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("ALTER TABLE bolum_agirliklari ALTER COLUMN agirlikli_varyans TYPE NUMERIC(12,4)")
    op.execute("ALTER TABLE bolum_agirliklari ALTER COLUMN yakinsama_skoru TYPE NUMERIC(10,4)")

    op.execute("ALTER TABLE meslekler DROP CONSTRAINT IF EXISTS meslekler_kaynak_check")
    op.execute("ALTER TABLE meslekler DROP CONSTRAINT IF EXISTS ck_meslek_kaynak")
    op.execute("ALTER TABLE meslekler ADD CONSTRAINT ck_meslek_kaynak CHECK (kaynak IN ('tmss_resmi','ek_guncel','esco'))")

    op.execute("UPDATE katmanlar SET normalizasyon_agirligi = 20 WHERE kod IN ('K1','K2','K3')")
    op.execute("UPDATE katmanlar SET normalizasyon_agirligi = 40 WHERE kod = 'K4'")

    op.execute("UPDATE sistem_parametreleri SET deger = '70' WHERE anahtar = 'k5_esik_puani'")
    op.execute("UPDATE sistem_parametreleri SET deger = '2' WHERE anahtar = 'k5_max_dal_sayisi'")

    op.execute("""
    UPDATE dallar d SET bagli_degisken_id = v.id
    FROM (VALUES ('D01','A5'),('D02','A2'),('D03','A9'),('D04','A5'),
                 ('D05','A1'),('D06','A3'),('D07','A4'),('D08','A6')) AS m(dal_kod, degisken_kod)
    JOIN degiskenler v ON v.kod = m.degisken_kod
    WHERE d.kod = m.dal_kod
    """)

    op.execute("""
    UPDATE bolum_dal_eslesme e SET dal_id = dl.id
    FROM bolumler b, dallar dl, (VALUES
    ('ACİL YARDIM VE AFET YÖNETİMİ', 'D01'),
    ('ADLİ BİLİMLER', 'D02'),
    ('ADLİ BİLİŞİM MÜHENDİSLİĞİ', 'D05'),
    ('AKSESUAR TASARIMI', 'D07'),
    ('AKTÜERYA BİLİMLERİ', 'D02'),
    ('ANTRENÖRLÜK EĞİTİMİ', 'D01'),
    ('ANTROPOLOJİ', 'D02'),
    ('ANİMASYON VE OYUN TASARIMI', 'D07'),
    ('ARKEOLOJİ', 'D02'),
    ('ASTRONOMİ VE UZAY BİLİMLERİ', 'D02'),
    ('AVRUPA BİRLİĞİ İLİŞKİLERİ', 'D03'),
    ('AYAKKABI TASARIMI VE ÜRETİMİ', 'D07'),
    ('AĞAÇ İŞLERİ ENDÜSTRİ MÜHENDİSLİĞİ', 'D08'),
    ('AİLE VE TÜKETİCİ BİLİMLERİ', 'D01'),
    ('BAHÇE BİTKİLERİ', 'D08'),
    ('BALIKÇILIK TEKNOLOJİSİ MÜHENDİSLİĞİ', 'D08'),
    ('BANKACILIK VE FİNANS', 'D03'),
    ('BANKACILIK VE SİGORTACILIK', 'D03'),
    ('BASIM TEKNOLOJİLERİ', 'D07'),
    ('BASIN VE YAYIN', 'D03'),
    ('BASKI SANATLARI', 'D07'),
    ('BESLENME VE DİYETETİK', 'D01'),
    ('BESTECİLİK VE ORKESTRA ŞEFLİĞİ', 'D07'),
    ('BİLEŞİK SANATLAR', 'D07'),
    ('BİLGİ GÜVENLİĞİ MÜHENDİSLİĞİ', 'D05'),
    ('BİLGİ VE BELGE YÖNETİMİ', 'D02'),
    ('BİLGİSAYAR BİLİMLERİ', 'D02'),
    ('BİLGİSAYAR MÜHENDİSLİĞİ', 'D05'),
    ('BİLGİSAYAR VE ÖĞRETİM TEKNOLOJİLERİ ÖĞRETMENLİĞİ', 'D06'),
    ('BİLİM TARİHİ', 'D02'),
    ('BİLİŞİM SİSTEMLERİ MÜHENDİSLİĞİ', 'D05'),
    ('BİTKİ KORUMA', 'D08'),
    ('BİTKİSEL ÜRETİM VE TEKNOLOJİLERİ', 'D08'),
    ('BİYOKİMYA', 'D04'),
    ('BİYOLOJİ', 'D04'),
    ('BİYOLOJİ ÖĞRETMENLİĞİ', 'D06'),
    ('BİYOMEDİKAL MÜHENDİSLİĞİ', 'D05'),
    ('BİYOMÜHENDİSLİK', 'D05'),
    ('BİYOSİSTEM MÜHENDİSLİĞİ', 'D08'),
    ('BİYOTEKNOLOJİ', 'D04'),
    ('CAM', 'D07'),
    ('CAZ VE POPÜLER MÜZİK', 'D07'),
    ('CEVHER HAZIRLAMA MÜHENDİSLİĞİ', 'D05'),
    ('COĞRAFYA', 'D02'),
    ('COĞRAFYA ÖĞRETMENLİĞİ', 'D06'),
    ('DENİZ ULAŞTIRMA İŞLETME MÜHENDİSLİĞİ', 'D08'),
    ('DENİZCİLİK İŞLETMELERİ YÖNETİMİ', 'D08'),
    ('DERİ MÜHENDİSLİĞİ', 'D08'),
    ('DOĞA KORUMA VE BİYOÇEŞİTLİLİK YÖNETİMİ', 'D04'),
    ('DRAMA VE OYUNCULUK', 'D07'),
    ('DRAMA YAZARLIĞI VE DRAMATURJİ', 'D07'),
    ('DİJİTAL MEDYA VE PAZARLAMA', 'D03'),
    ('DİJİTAL OYUN TASARIMI', 'D07'),
    ('DİL VE EDEBİYAT', 'D02'),
    ('DİL VE KONUŞMA TERAPİSİ', 'D01'),
    ('DİL ÖĞRETMENLİĞİ', 'D06'),
    ('DİŞ HEKİMLİĞİ', 'D01'),
    ('EBELİK', 'D01'),
    ('ECZACILIK', 'D01'),
    ('EGZERSİZ VE SPOR BİLİMLERİ', 'D01'),
    ('EKONOMETRİ', 'D03'),
    ('EKONOMİ', 'D03'),
    ('EKONOMİ VE FİNANS', 'D03'),
    ('EL SANATLARI', 'D07'),
    ('ELEKTRONİK TİCARET VE YÖNETİMİ', 'D03'),
    ('ELEKTRİK VE ELEKTRONİK MÜHENDİSLİĞİ', 'D05'),
    ('ENDÜSTRİ MÜHENDİSLİĞİ', 'D05'),
    ('ENDÜSTRİYEL TASARIM', 'D07'),
    ('ENDÜSTRİYEL TASARIM MÜHENDİSLİĞİ', 'D05'),
    ('ENERJİ SİSTEMLERİ MÜHENDİSLİĞİ', 'D05'),
    ('ENERJİ YÖNETİMİ', 'D03'),
    ('ERGOTERAPİ', 'D01'),
    ('FELSEFE', 'D02'),
    ('FELSEFE GRUBU ÖĞRETMENLİĞİ', 'D06'),
    ('FEN BİLGİSİ ÖĞRETMENLİĞİ', 'D06'),
    ('FOTONİK', 'D04'),
    ('FOTOĞRAF VE VİDEO', 'D07'),
    ('FİLM TASARIMI VE YAZARLIĞI', 'D07'),
    ('FİLM TASARIMI VE YÖNETMENLİĞİ', 'D07'),
    ('FİLM YAPIMI VE YAYINCILIK', 'D07'),
    ('FİNANS VE BANKACILIK', 'D03'),
    ('FİZYOTERAPİ VE REHABİLİTASYON', 'D01'),
    ('FİZİK', 'D02'),
    ('FİZİK MÜHENDİSLİĞİ', 'D05'),
    ('FİZİK ÖĞRETMENLİĞİ', 'D06'),
    ('GASTRONOMİ VE MUTFAK SANATLARI', 'D01'),
    ('GAYRİMENKUL GELİŞTİRME VE YÖNETİMİ', 'D03'),
    ('GAZETECİLİK', 'D03'),
    ('GELENEKSEL TÜRK SANATLARI', 'D07'),
    ('GEMİ MAKİNELERİ İŞLETME MÜHENDİSLİĞİ', 'D08'),
    ('GEMİ VE YAT TASARIMI', 'D07'),
    ('GEMİ İNŞAATI VE GEMİ MAKİNELERİ MÜHENDİSLİĞİ', 'D08'),
    ('GENETİK VE BİYOMÜHENDİSLİK', 'D04'),
    ('GERONTOLOJİ', 'D01'),
    ('GIDA MÜHENDİSLİĞİ', 'D08'),
    ('GRAFİK TASARIMI', 'D07'),
    ('GÖRSEL SANATLAR', 'D07'),
    ('GÖRSEL SANATLAR ÖĞRETMENLİĞİ', 'D06'),
    ('GÖRSEL İLETİŞİM TASARIMI', 'D07'),
    ('GÜMRÜK İŞLETME', 'D03'),
    ('GÜVERTE', 'D08'),
    ('GİRİŞİMCİLİK', 'D03'),
    ('HALI TASARIMI', 'D07'),
    ('HALI, KİLİM VE GELENEKSEL KUMAŞ DESENLERİ', 'D07'),
    ('HALKBİLİMİ', 'D02'),
    ('HALKLA İLİŞKİLER VE REKLAMCILIK', 'D03'),
    ('HARİTA MÜHENDİSLİĞİ', 'D05'),
    ('HASSAS TARIM VE TARIMSAL ROBOTLAR', 'D08'),
    ('HAT SANATI', 'D07'),
    ('HAVA TRAFİK KONTROLÜ', 'D05'),
    ('HAVACILIK ELEKTRİK VE ELEKTRONİĞİ', 'D05'),
    ('HAVACILIK VE UZAY MÜHENDİSLİĞİ', 'D05'),
    ('HAVACILIK YÖNETİMİ', 'D03'),
    ('HAYVANSAL ÜRETİM VE TEKNOLOJİLERİ', 'D08'),
    ('HEMŞİRELİK', 'D01'),
    ('HEYKEL', 'D07'),
    ('HUKUK', 'D03'),
    ('HİDROJEOLOJİ MÜHENDİSLİĞİ', 'D05'),
    ('HİDROLİK VE SU KAYNAKLARI MÜHENDİSLİĞİ', 'D05'),
    ('JEOFİZİK MÜHENDİSLİĞİ', 'D05'),
    ('JEOLOJİ MÜHENDİSLİĞİ', 'D05'),
    ('KAMU YÖNETİMİ', 'D03'),
    ('KANATLI HAYVAN YETİŞTİRİCİLİĞİ', 'D08'),
    ('KARŞILAŞTIRMALI EDEBİYAT', 'D02'),
    ('KENTSEL TASARIM VE PEYZAJ MİMARLIĞI', 'D07'),
    ('KONTROL VE OTOMASYON MÜHENDİSLİĞİ', 'D05'),
    ('KURGU, SES VE GÖRÜNTÜ YÖNETİMİ', 'D07'),
    ('KUYUMCULUK VE MÜCEVHER TASARIMI', 'D07'),
    ('KÜLTÜR VARLIKLARINI KORUMA VE ONARIM', 'D07'),
    ('KÜLTÜR VE İLETİŞİM BİLİMLERİ', 'D02'),
    ('KÜRESEL SİYASET VE ULUSLARARASI İLİŞKİLER', 'D03'),
    ('KİMYA', 'D04'),
    ('KİMYA MÜHENDİSLİĞİ', 'D05'),
    ('KİMYA ÖĞRETMENLİĞİ', 'D06'),
    ('KİMYA-BİYOLOJİ MÜHENDİSLİĞİ', 'D05'),
    ('LOJİSTİK YÖNETİMİ', 'D03'),
    ('LİDERLİK', 'D03'),
    ('MADEN MÜHENDİSLİĞİ', 'D05'),
    ('MAKİNE MÜHENDİSLİĞİ', 'D05'),
    ('MALZEME BİLİMİ VE MÜHENDİSLİĞİ', 'D05'),
    ('MALZEME BİLİMİ VE NANOTEKNOLOJİ MÜHENDİSLİĞİ', 'D05'),
    ('MALİYE', 'D03'),
    ('MATEMATİK', 'D02'),
    ('MATEMATİK MÜHENDİSLİĞİ', 'D05'),
    ('MATEMATİK VE BİLGİSAYAR BİLİMLERİ', 'D02'),
    ('MATEMATİK ÖĞRETMENLİĞİ', 'D06'),
    ('MEDYA VE İLETİŞİM', 'D03'),
    ('MEKATRONİK MÜHENDİSLİĞİ', 'D05'),
    ('METALURJİ VE MALZEME MÜHENDİSLİĞİ', 'D05'),
    ('MODA TASARIMI', 'D07'),
    ('MODERN DANS', 'D07'),
    ('MOLEKÜLER BİYOLOJİ VE GENETİK', 'D04'),
    ('MOLEKÜLER BİYOTEKNOLOJİ', 'D04'),
    ('MUHASEBE VE DENETİM', 'D03'),
    ('MUHASEBE VE FİNANS YÖNETİMİ', 'D03'),
    ('MÜTERCİM VE TERCÜMANLIK', 'D02'),
    ('MÜZECİLİK', 'D02'),
    ('MÜZİK', 'D07'),
    ('MÜZİK SES VE PERFORMANS', 'D07'),
    ('MÜZİK TEKNOLOJİSİ', 'D07'),
    ('MÜZİK TEORİSİ', 'D02'),
    ('MÜZİK ÇALGI', 'D07'),
    ('MÜZİK ÖĞRETMENLİĞİ', 'D06'),
    ('MÜZİKOLOJİ', 'D02'),
    ('MİMARLIK', 'D05'),
    ('NANOBİLİM VE NANOTEKNOLOJİ', 'D04'),
    ('NANOTEKNOLOJİ MÜHENDİSLİĞİ', 'D05'),
    ('NÜKLEER ENERJİ MÜHENDİSLİĞİ', 'D05'),
    ('ODYOLOJİ', 'D01'),
    ('OKUL ÖNCESİ ÖĞRETMENLİĞİ', 'D06'),
    ('OPTİK VE AKUSTİK MÜHENDİSLİĞİ', 'D05'),
    ('ORGANİK TARIM İŞLETMECİLİĞİ', 'D08'),
    ('ORKESTRA VE KORO ŞEFLİĞİ', 'D07'),
    ('ORMAN ENDÜSTRİSİ MÜHENDİSLİĞİ', 'D08'),
    ('ORMAN MÜHENDİSLİĞİ', 'D08'),
    ('ORTEZ VE PROTEZ', 'D01'),
    ('OTEL YÖNETİCİLİĞİ', 'D01'),
    ('OTOMOTİV MÜHENDİSLİĞİ', 'D05'),
    ('OYUNCULUK', 'D07'),
    ('PAZARLAMA', 'D03'),
    ('PAZARLAMA İLETİŞİMİ', 'D03'),
    ('PERFÜZYON', 'D01'),
    ('PETROL VE DOĞALGAZ MÜHENDİSLİĞİ', 'D05'),
    ('PEYZAJ MİMARLIĞI', 'D07'),
    ('PLASTİK SANATLAR VE RESİM', 'D07'),
    ('POLİMER MALZEME MÜHENDİSLİĞİ', 'D05'),
    ('POLİTİKA VE EKONOMİ', 'D03'),
    ('PSİKOLOJİ', 'D02'),
    ('PSİKOLOJİK DANIŞMANLIK VE REHBERLİK ÖĞRETMENLİĞİ', 'D06'),
    ('PİLOTAJ', 'D05'),
    ('RADYO, TELEVİZYON VE SİNEMA', 'D07'),
    ('RAYLI SİSTEMLER MÜHENDİSLİĞİ', 'D05'),
    ('REHBERLİK VE PSİKOLOJİK DANIŞMANLIK', 'D06'),
    ('REKLAMCILIK', 'D03'),
    ('REKREASYON YÖNETİMİ', 'D01'),
    ('RESİM', 'D07'),
    ('RESİM ÖĞRETMENLİĞİ', 'D06'),
    ('SAHNE DEKORU VE KOSTÜMÜ', 'D07'),
    ('SAHNE SANATLARI', 'D07'),
    ('SAHNE TASARIMI', 'D07'),
    ('SAHNE VE GÖSTERİ SANATLARI YÖNETİMİ', 'D03'),
    ('SANAT TARİHİ', 'D02'),
    ('SANAT VE KÜLTÜR YÖNETİMİ', 'D03'),
    ('SAÇ VE GÜZELLİK UYGULAMALARI', 'D01'),
    ('SAĞLIK YÖNETİMİ', 'D01'),
    ('SERAMİK VE CAM', 'D07'),
    ('SERMAYE PİYASASI', 'D03'),
    ('SES SANATLARI TASARIMI', 'D07'),
    ('SEYAHAT İŞLETMECİLİĞİ VE TURİZM REHBERLİĞİ', 'D01'),
    ('SINIF ÖĞRETMENLİĞİ', 'D06'),
    ('SOSYAL BİLGİLER ÖĞRETMENLİĞİ', 'D06'),
    ('SOSYAL HİZMET', 'D01'),
    ('SOSYOLOJİ', 'D02'),
    ('SPOR YÖNETİCİLİĞİ', 'D01'),
    ('SPOR ÖĞRETMENLİĞİ', 'D06'),
    ('SU BİLİMLERİ VE MÜHENDİSLİĞİ', 'D04'),
    ('SU ÜRÜNLERİ MÜHENDİSLİĞİ', 'D08'),
    ('SÜT TEKNOLOJİSİ', 'D08'),
    ('SİBER GÜVENLİK MÜHENDİSLİĞİ', 'D05'),
    ('SİGORTACILIK VE AKTÜERYA BİLİMLERİ', 'D03'),
    ('SİGORTACILIK VE RİSK YÖNETİMİ', 'D03'),
    ('SİNEMA VE DİJİTAL MEDYA', 'D07'),
    ('SİVİL HAVA ULAŞTIRMA İŞLETMECİLİĞİ', 'D03'),
    ('SİYASET BİLİMİ VE KAMU YÖNETİMİ', 'D03'),
    ('SİYASET BİLİMİ VE ULUSLARARASI İLİŞKİLER', 'D03'),
    ('TAKI TASARIMI VE İMALATI', 'D07'),
    ('TARIM EKONOMİSİ', 'D08'),
    ('TARIM MAKİNELERİ VE TEKNOLOJİLERİ MÜHENDİSLİĞİ', 'D08'),
    ('TARIM TİCARETİ VE İŞLETMECİLİĞİ', 'D08'),
    ('TARIMSAL BİYOTEKNOLOJİ', 'D04'),
    ('TARIMSAL GENETİK MÜHENDİSLİĞİ', 'D04'),
    ('TARIMSAL YAPILAR VE SULAMA', 'D08'),
    ('TARLA BİTKİLERİ', 'D08'),
    ('TARİH', 'D02'),
    ('TARİH ÖĞRETMENLİĞİ', 'D06'),
    ('TEKNOLOJİ GİRİŞİMCİLİĞİ', 'D03'),
    ('TEKSTİL MÜHENDİSLİĞİ', 'D08'),
    ('TEKSTİL TASARIMI', 'D07'),
    ('TEKSTİL VE MODA TASARIMI', 'D07'),
    ('TELEVİZYON HABERCİLİĞİ VE PROGRAMCILIĞI', 'D03'),
    ('TEZHİP-MİNYATÜR VE EBRU', 'D07'),
    ('TIP', 'D01'),
    ('TIP MÜHENDİSLİĞİ', 'D05'),
    ('TOHUM BİLİMİ VE TEKNOLOJİSİ', 'D08'),
    ('TOPRAK BİLİMİ VE BİTKİ BESLEME', 'D04'),
    ('TURİZM REHBERLİĞİ', 'D01'),
    ('TURİZM VE KONAKLAMA İŞLETMECİLİĞİ', 'D01'),
    ('TURİZM İŞLETMECİLİĞİ', 'D01'),
    ('TÜRK HALK OYUNLARI', 'D07'),
    ('TÜRK HALKBİLİMİ', 'D02'),
    ('TİYATRO', 'D07'),
    ('TİYATRO ELEŞTİRMENLİĞİ VE DRAMATURJİ', 'D07'),
    ('ULAŞTIRMA VE TRAFİK MÜHENDİSLİĞİ', 'D05'),
    ('ULUSLARARASI EKONOMİK İLİŞKİLER', 'D03'),
    ('ULUSLARARASI FİNANS', 'D03'),
    ('ULUSLARARASI GİRİŞİMCİLİK', 'D03'),
    ('ULUSLARARASI HUKUK', 'D03'),
    ('ULUSLARARASI TİCARET VE LOJİSTİK', 'D03'),
    ('ULUSLARARASI İLİŞKİLER', 'D03'),
    ('ULUSLARARASI İŞLETMECİLİK VE TİCARET', 'D03'),
    ('UZAY BİLİMLERİ VE TEKNOLOJİLERİ', 'D04'),
    ('UZAY MÜHENDİSLİĞİ', 'D05'),
    ('UÇAK BAKIM VE ONARIM', 'D05'),
    ('UÇAK MÜHENDİSLİĞİ', 'D05'),
    ('VERİ BİLİMİ VE ANALİTİĞİ', 'D05'),
    ('VETERİNERLİK', 'D01'),
    ('YABAN HAYATI EKOLOJİSİ VE YÖNETİMİ', 'D04'),
    ('YAPAY ZEKA MÜHENDİSLİĞİ', 'D05'),
    ('YAPAY ZEKA VE MAKİNE ÖĞRENMESİ', 'D05'),
    ('YAPAY ZEKA VE VERİ MÜHENDİSLİĞİ', 'D05'),
    ('YAZILIM MÜHENDİSLİĞİ', 'D05'),
    ('YENİ MEDYA VE GAZETECİLİK', 'D03'),
    ('YENİ MEDYA VE İLETİŞİM', 'D03'),
    ('YEREL YÖNETİMLER', 'D03'),
    ('YÖNETİM BİLİŞİM SİSTEMLERİ', 'D03'),
    ('YİYECEK VE İÇECEK İŞLETMECİLİĞİ', 'D01'),
    ('ZOOTEKNİ', 'D08'),
    ('ÇALGI TEKNOLOJİLERİ', 'D07'),
    ('ÇALIŞMA EKONOMİSİ VE ENDÜSTRİ İLİŞKİLERİ', 'D03'),
    ('ÇEVRE MÜHENDİSLİĞİ', 'D05'),
    ('ÇOCUK GELİŞİMİ', 'D01'),
    ('ÇİNİ TASARIMI VE ONARIMI', 'D07'),
    ('ÇİZGİ FİLM VE ANİMASYON', 'D07'),
    ('ÖZEL EĞİTİM ÖĞRETMENLİĞİ', 'D06'),
    ('İKLİM BİLİMİ VE METEOROLOJİ MÜHENDİSLİĞİ', 'D04'),
    ('İKTİSAT', 'D03'),
    ('İLAHİYAT', 'D02'),
    ('İLETİŞİM BİLİMLERİ', 'D03'),
    ('İLETİŞİM TASARIMI VE YÖNETİMİ', 'D03'),
    ('İLKÖĞRETİM MATEMATİK ÖĞRETMENLİĞİ', 'D06'),
    ('İMALAT MÜHENDİSLİĞİ', 'D05'),
    ('İNSAN KAYNAKLARI YÖNETİMİ', 'D03'),
    ('İNŞAAT MÜHENDİSLİĞİ', 'D05'),
    ('İSLAM BİLİMLERİ', 'D02'),
    ('İSLAM İKTİSADI VE FİNANS', 'D03'),
    ('İSTATİSTİK', 'D02'),
    ('İÇ MİMARLIK VE ÇEVRE TASARIMI', 'D07'),
    ('İŞ SAĞLIĞI VE GÜVENLİĞİ', 'D01'),
    ('İŞLETME', 'D03'),
    ('İŞLETME MÜHENDİSLİĞİ', 'D05'),
    ('ŞEHİR VE BÖLGE PLANLAMA', 'D05')
    ) AS v(bolum_adi, dal_kod)
    WHERE b.ad = v.bolum_adi AND dl.kod = v.dal_kod AND e.bolum_id = b.id
    """)


def downgrade():
    pass  # veri düzeltmeleri geri alınmaz
